/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the ChatCompletionResponseChoicesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatCompletionResponseChoicesInner{}

// ChatCompletionResponseChoicesInner struct for ChatCompletionResponseChoicesInner
type ChatCompletionResponseChoicesInner struct {
	Index *int32 `json:"index,omitempty"`
	Message *ChatMessage `json:"message,omitempty"`
	FinishReason *string `json:"finish_reason,omitempty"`
}

// NewChatCompletionResponseChoicesInner instantiates a new ChatCompletionResponseChoicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatCompletionResponseChoicesInner() *ChatCompletionResponseChoicesInner {
	this := ChatCompletionResponseChoicesInner{}
	return &this
}

// NewChatCompletionResponseChoicesInnerWithDefaults instantiates a new ChatCompletionResponseChoicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatCompletionResponseChoicesInnerWithDefaults() *ChatCompletionResponseChoicesInner {
	this := ChatCompletionResponseChoicesInner{}
	return &this
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *ChatCompletionResponseChoicesInner) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatCompletionResponseChoicesInner) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *ChatCompletionResponseChoicesInner) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *ChatCompletionResponseChoicesInner) SetIndex(v int32) {
	o.Index = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ChatCompletionResponseChoicesInner) GetMessage() ChatMessage {
	if o == nil || IsNil(o.Message) {
		var ret ChatMessage
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatCompletionResponseChoicesInner) GetMessageOk() (*ChatMessage, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ChatCompletionResponseChoicesInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given ChatMessage and assigns it to the Message field.
func (o *ChatCompletionResponseChoicesInner) SetMessage(v ChatMessage) {
	o.Message = &v
}

// GetFinishReason returns the FinishReason field value if set, zero value otherwise.
func (o *ChatCompletionResponseChoicesInner) GetFinishReason() string {
	if o == nil || IsNil(o.FinishReason) {
		var ret string
		return ret
	}
	return *o.FinishReason
}

// GetFinishReasonOk returns a tuple with the FinishReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatCompletionResponseChoicesInner) GetFinishReasonOk() (*string, bool) {
	if o == nil || IsNil(o.FinishReason) {
		return nil, false
	}
	return o.FinishReason, true
}

// HasFinishReason returns a boolean if a field has been set.
func (o *ChatCompletionResponseChoicesInner) HasFinishReason() bool {
	if o != nil && !IsNil(o.FinishReason) {
		return true
	}

	return false
}

// SetFinishReason gets a reference to the given string and assigns it to the FinishReason field.
func (o *ChatCompletionResponseChoicesInner) SetFinishReason(v string) {
	o.FinishReason = &v
}

func (o ChatCompletionResponseChoicesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatCompletionResponseChoicesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.FinishReason) {
		toSerialize["finish_reason"] = o.FinishReason
	}
	return toSerialize, nil
}

type NullableChatCompletionResponseChoicesInner struct {
	value *ChatCompletionResponseChoicesInner
	isSet bool
}

func (v NullableChatCompletionResponseChoicesInner) Get() *ChatCompletionResponseChoicesInner {
	return v.value
}

func (v *NullableChatCompletionResponseChoicesInner) Set(val *ChatCompletionResponseChoicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionResponseChoicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionResponseChoicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionResponseChoicesInner(val *ChatCompletionResponseChoicesInner) *NullableChatCompletionResponseChoicesInner {
	return &NullableChatCompletionResponseChoicesInner{value: val, isSet: true}
}

func (v NullableChatCompletionResponseChoicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionResponseChoicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


