/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the CacheKeyEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheKeyEntry{}

// CacheKeyEntry struct for CacheKeyEntry
type CacheKeyEntry struct {
	// Cache key (project prefix stripped)
	Key *string `json:"key,omitempty"`
	// Unix timestamp when this key expires (null if no TTL)
	Expiration *int32 `json:"expiration,omitempty"`
}

// NewCacheKeyEntry instantiates a new CacheKeyEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheKeyEntry() *CacheKeyEntry {
	this := CacheKeyEntry{}
	return &this
}

// NewCacheKeyEntryWithDefaults instantiates a new CacheKeyEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheKeyEntryWithDefaults() *CacheKeyEntry {
	this := CacheKeyEntry{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *CacheKeyEntry) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheKeyEntry) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *CacheKeyEntry) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *CacheKeyEntry) SetKey(v string) {
	o.Key = &v
}

// GetExpiration returns the Expiration field value if set, zero value otherwise.
func (o *CacheKeyEntry) GetExpiration() int32 {
	if o == nil || IsNil(o.Expiration) {
		var ret int32
		return ret
	}
	return *o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheKeyEntry) GetExpirationOk() (*int32, bool) {
	if o == nil || IsNil(o.Expiration) {
		return nil, false
	}
	return o.Expiration, true
}

// HasExpiration returns a boolean if a field has been set.
func (o *CacheKeyEntry) HasExpiration() bool {
	if o != nil && !IsNil(o.Expiration) {
		return true
	}

	return false
}

// SetExpiration gets a reference to the given int32 and assigns it to the Expiration field.
func (o *CacheKeyEntry) SetExpiration(v int32) {
	o.Expiration = &v
}

func (o CacheKeyEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheKeyEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Expiration) {
		toSerialize["expiration"] = o.Expiration
	}
	return toSerialize, nil
}

type NullableCacheKeyEntry struct {
	value *CacheKeyEntry
	isSet bool
}

func (v NullableCacheKeyEntry) Get() *CacheKeyEntry {
	return v.value
}

func (v *NullableCacheKeyEntry) Set(val *CacheKeyEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheKeyEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheKeyEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheKeyEntry(val *CacheKeyEntry) *NullableCacheKeyEntry {
	return &NullableCacheKeyEntry{value: val, isSet: true}
}

func (v NullableCacheKeyEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheKeyEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


