/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the StorageUpload200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageUpload200Response{}

// StorageUpload200Response struct for StorageUpload200Response
type StorageUpload200Response struct {
	Url *string `json:"url,omitempty"`
}

// NewStorageUpload200Response instantiates a new StorageUpload200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageUpload200Response() *StorageUpload200Response {
	this := StorageUpload200Response{}
	return &this
}

// NewStorageUpload200ResponseWithDefaults instantiates a new StorageUpload200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageUpload200ResponseWithDefaults() *StorageUpload200Response {
	this := StorageUpload200Response{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *StorageUpload200Response) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageUpload200Response) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *StorageUpload200Response) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *StorageUpload200Response) SetUrl(v string) {
	o.Url = &v
}

func (o StorageUpload200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageUpload200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableStorageUpload200Response struct {
	value *StorageUpload200Response
	isSet bool
}

func (v NullableStorageUpload200Response) Get() *StorageUpload200Response {
	return v.value
}

func (v *NullableStorageUpload200Response) Set(val *StorageUpload200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageUpload200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageUpload200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageUpload200Response(val *StorageUpload200Response) *NullableStorageUpload200Response {
	return &NullableStorageUpload200Response{value: val, isSet: true}
}

func (v NullableStorageUpload200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageUpload200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


