/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the GatewayBillingLog200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayBillingLog200Response{}

// GatewayBillingLog200Response struct for GatewayBillingLog200Response
type GatewayBillingLog200Response struct {
	Success *bool `json:"success,omitempty"`
	LoggedUnits *int32 `json:"loggedUnits,omitempty"`
}

// NewGatewayBillingLog200Response instantiates a new GatewayBillingLog200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayBillingLog200Response() *GatewayBillingLog200Response {
	this := GatewayBillingLog200Response{}
	return &this
}

// NewGatewayBillingLog200ResponseWithDefaults instantiates a new GatewayBillingLog200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayBillingLog200ResponseWithDefaults() *GatewayBillingLog200Response {
	this := GatewayBillingLog200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GatewayBillingLog200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayBillingLog200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GatewayBillingLog200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GatewayBillingLog200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetLoggedUnits returns the LoggedUnits field value if set, zero value otherwise.
func (o *GatewayBillingLog200Response) GetLoggedUnits() int32 {
	if o == nil || IsNil(o.LoggedUnits) {
		var ret int32
		return ret
	}
	return *o.LoggedUnits
}

// GetLoggedUnitsOk returns a tuple with the LoggedUnits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayBillingLog200Response) GetLoggedUnitsOk() (*int32, bool) {
	if o == nil || IsNil(o.LoggedUnits) {
		return nil, false
	}
	return o.LoggedUnits, true
}

// HasLoggedUnits returns a boolean if a field has been set.
func (o *GatewayBillingLog200Response) HasLoggedUnits() bool {
	if o != nil && !IsNil(o.LoggedUnits) {
		return true
	}

	return false
}

// SetLoggedUnits gets a reference to the given int32 and assigns it to the LoggedUnits field.
func (o *GatewayBillingLog200Response) SetLoggedUnits(v int32) {
	o.LoggedUnits = &v
}

func (o GatewayBillingLog200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayBillingLog200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.LoggedUnits) {
		toSerialize["loggedUnits"] = o.LoggedUnits
	}
	return toSerialize, nil
}

type NullableGatewayBillingLog200Response struct {
	value *GatewayBillingLog200Response
	isSet bool
}

func (v NullableGatewayBillingLog200Response) Get() *GatewayBillingLog200Response {
	return v.value
}

func (v *NullableGatewayBillingLog200Response) Set(val *GatewayBillingLog200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayBillingLog200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayBillingLog200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayBillingLog200Response(val *GatewayBillingLog200Response) *NullableGatewayBillingLog200Response {
	return &NullableGatewayBillingLog200Response{value: val, isSet: true}
}

func (v NullableGatewayBillingLog200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayBillingLog200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


