/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the GatewayGetWallet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayGetWallet200Response{}

// GatewayGetWallet200Response struct for GatewayGetWallet200Response
type GatewayGetWallet200Response struct {
	Wallet *TokenWallet `json:"wallet,omitempty"`
}

// NewGatewayGetWallet200Response instantiates a new GatewayGetWallet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayGetWallet200Response() *GatewayGetWallet200Response {
	this := GatewayGetWallet200Response{}
	return &this
}

// NewGatewayGetWallet200ResponseWithDefaults instantiates a new GatewayGetWallet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayGetWallet200ResponseWithDefaults() *GatewayGetWallet200Response {
	this := GatewayGetWallet200Response{}
	return &this
}

// GetWallet returns the Wallet field value if set, zero value otherwise.
func (o *GatewayGetWallet200Response) GetWallet() TokenWallet {
	if o == nil || IsNil(o.Wallet) {
		var ret TokenWallet
		return ret
	}
	return *o.Wallet
}

// GetWalletOk returns a tuple with the Wallet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayGetWallet200Response) GetWalletOk() (*TokenWallet, bool) {
	if o == nil || IsNil(o.Wallet) {
		return nil, false
	}
	return o.Wallet, true
}

// HasWallet returns a boolean if a field has been set.
func (o *GatewayGetWallet200Response) HasWallet() bool {
	if o != nil && !IsNil(o.Wallet) {
		return true
	}

	return false
}

// SetWallet gets a reference to the given TokenWallet and assigns it to the Wallet field.
func (o *GatewayGetWallet200Response) SetWallet(v TokenWallet) {
	o.Wallet = &v
}

func (o GatewayGetWallet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayGetWallet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Wallet) {
		toSerialize["wallet"] = o.Wallet
	}
	return toSerialize, nil
}

type NullableGatewayGetWallet200Response struct {
	value *GatewayGetWallet200Response
	isSet bool
}

func (v NullableGatewayGetWallet200Response) Get() *GatewayGetWallet200Response {
	return v.value
}

func (v *NullableGatewayGetWallet200Response) Set(val *GatewayGetWallet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayGetWallet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayGetWallet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayGetWallet200Response(val *GatewayGetWallet200Response) *NullableGatewayGetWallet200Response {
	return &NullableGatewayGetWallet200Response{value: val, isSet: true}
}

func (v NullableGatewayGetWallet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayGetWallet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


