/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DbBatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DbBatchRequest{}

// DbBatchRequest struct for DbBatchRequest
type DbBatchRequest struct {
	// Array of queries to execute (max 25)
	Queries []DbBatchRequestQueriesInner `json:"queries"`
}

type _DbBatchRequest DbBatchRequest

// NewDbBatchRequest instantiates a new DbBatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbBatchRequest(queries []DbBatchRequestQueriesInner) *DbBatchRequest {
	this := DbBatchRequest{}
	this.Queries = queries
	return &this
}

// NewDbBatchRequestWithDefaults instantiates a new DbBatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbBatchRequestWithDefaults() *DbBatchRequest {
	this := DbBatchRequest{}
	return &this
}

// GetQueries returns the Queries field value
func (o *DbBatchRequest) GetQueries() []DbBatchRequestQueriesInner {
	if o == nil {
		var ret []DbBatchRequestQueriesInner
		return ret
	}

	return o.Queries
}

// GetQueriesOk returns a tuple with the Queries field value
// and a boolean to check if the value has been set.
func (o *DbBatchRequest) GetQueriesOk() ([]DbBatchRequestQueriesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Queries, true
}

// SetQueries sets field value
func (o *DbBatchRequest) SetQueries(v []DbBatchRequestQueriesInner) {
	o.Queries = v
}

func (o DbBatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DbBatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["queries"] = o.Queries
	return toSerialize, nil
}

func (o *DbBatchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"queries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDbBatchRequest := _DbBatchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDbBatchRequest)

	if err != nil {
		return err
	}

	*o = DbBatchRequest(varDbBatchRequest)

	return err
}

type NullableDbBatchRequest struct {
	value *DbBatchRequest
	isSet bool
}

func (v NullableDbBatchRequest) Get() *DbBatchRequest {
	return v.value
}

func (v *NullableDbBatchRequest) Set(val *DbBatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDbBatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDbBatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbBatchRequest(val *DbBatchRequest) *NullableDbBatchRequest {
	return &NullableDbBatchRequest{value: val, isSet: true}
}

func (v NullableDbBatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbBatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


