/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StorageCopyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageCopyRequest{}

// StorageCopyRequest struct for StorageCopyRequest
type StorageCopyRequest struct {
	SourceKey string `json:"sourceKey"`
	DestKey string `json:"destKey"`
}

type _StorageCopyRequest StorageCopyRequest

// NewStorageCopyRequest instantiates a new StorageCopyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageCopyRequest(sourceKey string, destKey string) *StorageCopyRequest {
	this := StorageCopyRequest{}
	this.SourceKey = sourceKey
	this.DestKey = destKey
	return &this
}

// NewStorageCopyRequestWithDefaults instantiates a new StorageCopyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageCopyRequestWithDefaults() *StorageCopyRequest {
	this := StorageCopyRequest{}
	return &this
}

// GetSourceKey returns the SourceKey field value
func (o *StorageCopyRequest) GetSourceKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceKey
}

// GetSourceKeyOk returns a tuple with the SourceKey field value
// and a boolean to check if the value has been set.
func (o *StorageCopyRequest) GetSourceKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceKey, true
}

// SetSourceKey sets field value
func (o *StorageCopyRequest) SetSourceKey(v string) {
	o.SourceKey = v
}

// GetDestKey returns the DestKey field value
func (o *StorageCopyRequest) GetDestKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestKey
}

// GetDestKeyOk returns a tuple with the DestKey field value
// and a boolean to check if the value has been set.
func (o *StorageCopyRequest) GetDestKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestKey, true
}

// SetDestKey sets field value
func (o *StorageCopyRequest) SetDestKey(v string) {
	o.DestKey = v
}

func (o StorageCopyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageCopyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sourceKey"] = o.SourceKey
	toSerialize["destKey"] = o.DestKey
	return toSerialize, nil
}

func (o *StorageCopyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sourceKey",
		"destKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageCopyRequest := _StorageCopyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStorageCopyRequest)

	if err != nil {
		return err
	}

	*o = StorageCopyRequest(varStorageCopyRequest)

	return err
}

type NullableStorageCopyRequest struct {
	value *StorageCopyRequest
	isSet bool
}

func (v NullableStorageCopyRequest) Get() *StorageCopyRequest {
	return v.value
}

func (v *NullableStorageCopyRequest) Set(val *StorageCopyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageCopyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageCopyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageCopyRequest(val *StorageCopyRequest) *NullableStorageCopyRequest {
	return &NullableStorageCopyRequest{value: val, isSet: true}
}

func (v NullableStorageCopyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageCopyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


