/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the QueueGetJob200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueGetJob200Response{}

// QueueGetJob200Response struct for QueueGetJob200Response
type QueueGetJob200Response struct {
	Job NullableJobRecord `json:"job,omitempty"`
	Exists *bool `json:"exists,omitempty"`
}

// NewQueueGetJob200Response instantiates a new QueueGetJob200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueGetJob200Response() *QueueGetJob200Response {
	this := QueueGetJob200Response{}
	return &this
}

// NewQueueGetJob200ResponseWithDefaults instantiates a new QueueGetJob200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueGetJob200ResponseWithDefaults() *QueueGetJob200Response {
	this := QueueGetJob200Response{}
	return &this
}

// GetJob returns the Job field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueueGetJob200Response) GetJob() JobRecord {
	if o == nil || IsNil(o.Job.Get()) {
		var ret JobRecord
		return ret
	}
	return *o.Job.Get()
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueGetJob200Response) GetJobOk() (*JobRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Job.Get(), o.Job.IsSet()
}

// HasJob returns a boolean if a field has been set.
func (o *QueueGetJob200Response) HasJob() bool {
	if o != nil && o.Job.IsSet() {
		return true
	}

	return false
}

// SetJob gets a reference to the given NullableJobRecord and assigns it to the Job field.
func (o *QueueGetJob200Response) SetJob(v JobRecord) {
	o.Job.Set(&v)
}
// SetJobNil sets the value for Job to be an explicit nil
func (o *QueueGetJob200Response) SetJobNil() {
	o.Job.Set(nil)
}

// UnsetJob ensures that no value is present for Job, not even an explicit nil
func (o *QueueGetJob200Response) UnsetJob() {
	o.Job.Unset()
}

// GetExists returns the Exists field value if set, zero value otherwise.
func (o *QueueGetJob200Response) GetExists() bool {
	if o == nil || IsNil(o.Exists) {
		var ret bool
		return ret
	}
	return *o.Exists
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueGetJob200Response) GetExistsOk() (*bool, bool) {
	if o == nil || IsNil(o.Exists) {
		return nil, false
	}
	return o.Exists, true
}

// HasExists returns a boolean if a field has been set.
func (o *QueueGetJob200Response) HasExists() bool {
	if o != nil && !IsNil(o.Exists) {
		return true
	}

	return false
}

// SetExists gets a reference to the given bool and assigns it to the Exists field.
func (o *QueueGetJob200Response) SetExists(v bool) {
	o.Exists = &v
}

func (o QueueGetJob200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueGetJob200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Job.IsSet() {
		toSerialize["job"] = o.Job.Get()
	}
	if !IsNil(o.Exists) {
		toSerialize["exists"] = o.Exists
	}
	return toSerialize, nil
}

type NullableQueueGetJob200Response struct {
	value *QueueGetJob200Response
	isSet bool
}

func (v NullableQueueGetJob200Response) Get() *QueueGetJob200Response {
	return v.value
}

func (v *NullableQueueGetJob200Response) Set(val *QueueGetJob200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueGetJob200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueGetJob200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueGetJob200Response(val *QueueGetJob200Response) *NullableQueueGetJob200Response {
	return &NullableQueueGetJob200Response{value: val, isSet: true}
}

func (v NullableQueueGetJob200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueGetJob200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


