/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteByTypeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteByTypeRequest{}

// DeleteByTypeRequest struct for DeleteByTypeRequest
type DeleteByTypeRequest struct {
	Type string `json:"type"`
}

type _DeleteByTypeRequest DeleteByTypeRequest

// NewDeleteByTypeRequest instantiates a new DeleteByTypeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteByTypeRequest(type_ string) *DeleteByTypeRequest {
	this := DeleteByTypeRequest{}
	this.Type = type_
	return &this
}

// NewDeleteByTypeRequestWithDefaults instantiates a new DeleteByTypeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteByTypeRequestWithDefaults() *DeleteByTypeRequest {
	this := DeleteByTypeRequest{}
	return &this
}

// GetType returns the Type field value
func (o *DeleteByTypeRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DeleteByTypeRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DeleteByTypeRequest) SetType(v string) {
	o.Type = v
}

func (o DeleteByTypeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteByTypeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *DeleteByTypeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteByTypeRequest := _DeleteByTypeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteByTypeRequest)

	if err != nil {
		return err
	}

	*o = DeleteByTypeRequest(varDeleteByTypeRequest)

	return err
}

type NullableDeleteByTypeRequest struct {
	value *DeleteByTypeRequest
	isSet bool
}

func (v NullableDeleteByTypeRequest) Get() *DeleteByTypeRequest {
	return v.value
}

func (v *NullableDeleteByTypeRequest) Set(val *DeleteByTypeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteByTypeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteByTypeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteByTypeRequest(val *DeleteByTypeRequest) *NullableDeleteByTypeRequest {
	return &NullableDeleteByTypeRequest{value: val, isSet: true}
}

func (v NullableDeleteByTypeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteByTypeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


