/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueueEnqueueRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueEnqueueRequest{}

// QueueEnqueueRequest struct for QueueEnqueueRequest
type QueueEnqueueRequest struct {
	Type string `json:"type"`
	Data map[string]interface{} `json:"data"`
	// Delay in seconds before processing
	Delay *int32 `json:"delay,omitempty"`
}

type _QueueEnqueueRequest QueueEnqueueRequest

// NewQueueEnqueueRequest instantiates a new QueueEnqueueRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueEnqueueRequest(type_ string, data map[string]interface{}) *QueueEnqueueRequest {
	this := QueueEnqueueRequest{}
	this.Type = type_
	this.Data = data
	return &this
}

// NewQueueEnqueueRequestWithDefaults instantiates a new QueueEnqueueRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueEnqueueRequestWithDefaults() *QueueEnqueueRequest {
	this := QueueEnqueueRequest{}
	return &this
}

// GetType returns the Type field value
func (o *QueueEnqueueRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *QueueEnqueueRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *QueueEnqueueRequest) SetType(v string) {
	o.Type = v
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *QueueEnqueueRequest) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueueEnqueueRequest) GetDataOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *QueueEnqueueRequest) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetDelay returns the Delay field value if set, zero value otherwise.
func (o *QueueEnqueueRequest) GetDelay() int32 {
	if o == nil || IsNil(o.Delay) {
		var ret int32
		return ret
	}
	return *o.Delay
}

// GetDelayOk returns a tuple with the Delay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueEnqueueRequest) GetDelayOk() (*int32, bool) {
	if o == nil || IsNil(o.Delay) {
		return nil, false
	}
	return o.Delay, true
}

// HasDelay returns a boolean if a field has been set.
func (o *QueueEnqueueRequest) HasDelay() bool {
	if o != nil && !IsNil(o.Delay) {
		return true
	}

	return false
}

// SetDelay gets a reference to the given int32 and assigns it to the Delay field.
func (o *QueueEnqueueRequest) SetDelay(v int32) {
	o.Delay = &v
}

func (o QueueEnqueueRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueEnqueueRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Delay) {
		toSerialize["delay"] = o.Delay
	}
	return toSerialize, nil
}

func (o *QueueEnqueueRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueueEnqueueRequest := _QueueEnqueueRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueueEnqueueRequest)

	if err != nil {
		return err
	}

	*o = QueueEnqueueRequest(varQueueEnqueueRequest)

	return err
}

type NullableQueueEnqueueRequest struct {
	value *QueueEnqueueRequest
	isSet bool
}

func (v NullableQueueEnqueueRequest) Get() *QueueEnqueueRequest {
	return v.value
}

func (v *NullableQueueEnqueueRequest) Set(val *QueueEnqueueRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueEnqueueRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueEnqueueRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueEnqueueRequest(val *QueueEnqueueRequest) *NullableQueueEnqueueRequest {
	return &NullableQueueEnqueueRequest{value: val, isSet: true}
}

func (v NullableQueueEnqueueRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueEnqueueRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


