/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchUpdateRequest{}

// SearchUpdateRequest struct for SearchUpdateRequest
type SearchUpdateRequest struct {
	// ID of the item to update
	Id string `json:"id"`
	// New text content to re-embed
	Content string `json:"content"`
	// New type (replaces existing type)
	Type *string `json:"type,omitempty"`
	// New metadata (replaces existing metadata)
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _SearchUpdateRequest SearchUpdateRequest

// NewSearchUpdateRequest instantiates a new SearchUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchUpdateRequest(id string, content string) *SearchUpdateRequest {
	this := SearchUpdateRequest{}
	this.Id = id
	this.Content = content
	return &this
}

// NewSearchUpdateRequestWithDefaults instantiates a new SearchUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchUpdateRequestWithDefaults() *SearchUpdateRequest {
	this := SearchUpdateRequest{}
	return &this
}

// GetId returns the Id field value
func (o *SearchUpdateRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SearchUpdateRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SearchUpdateRequest) SetId(v string) {
	o.Id = v
}

// GetContent returns the Content field value
func (o *SearchUpdateRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *SearchUpdateRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *SearchUpdateRequest) SetContent(v string) {
	o.Content = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SearchUpdateRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchUpdateRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SearchUpdateRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SearchUpdateRequest) SetType(v string) {
	o.Type = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchUpdateRequest) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchUpdateRequest) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *SearchUpdateRequest) HasMetadata() bool {
	if o != nil && IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *SearchUpdateRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o SearchUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["content"] = o.Content
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *SearchUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchUpdateRequest := _SearchUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchUpdateRequest)

	if err != nil {
		return err
	}

	*o = SearchUpdateRequest(varSearchUpdateRequest)

	return err
}

type NullableSearchUpdateRequest struct {
	value *SearchUpdateRequest
	isSet bool
}

func (v NullableSearchUpdateRequest) Get() *SearchUpdateRequest {
	return v.value
}

func (v *NullableSearchUpdateRequest) Set(val *SearchUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchUpdateRequest(val *SearchUpdateRequest) *NullableSearchUpdateRequest {
	return &NullableSearchUpdateRequest{value: val, isSet: true}
}

func (v NullableSearchUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


