/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"time"
)

// checks if the StorageMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageMetadata{}

// StorageMetadata struct for StorageMetadata
type StorageMetadata struct {
	Exists *bool `json:"exists,omitempty"`
	// File size in bytes
	Size *int32 `json:"size,omitempty"`
	ContentType *string `json:"contentType,omitempty"`
	LastModified *time.Time `json:"lastModified,omitempty"`
	Etag *string `json:"etag,omitempty"`
}

// NewStorageMetadata instantiates a new StorageMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageMetadata() *StorageMetadata {
	this := StorageMetadata{}
	return &this
}

// NewStorageMetadataWithDefaults instantiates a new StorageMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageMetadataWithDefaults() *StorageMetadata {
	this := StorageMetadata{}
	return &this
}

// GetExists returns the Exists field value if set, zero value otherwise.
func (o *StorageMetadata) GetExists() bool {
	if o == nil || IsNil(o.Exists) {
		var ret bool
		return ret
	}
	return *o.Exists
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageMetadata) GetExistsOk() (*bool, bool) {
	if o == nil || IsNil(o.Exists) {
		return nil, false
	}
	return o.Exists, true
}

// HasExists returns a boolean if a field has been set.
func (o *StorageMetadata) HasExists() bool {
	if o != nil && !IsNil(o.Exists) {
		return true
	}

	return false
}

// SetExists gets a reference to the given bool and assigns it to the Exists field.
func (o *StorageMetadata) SetExists(v bool) {
	o.Exists = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *StorageMetadata) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageMetadata) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *StorageMetadata) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *StorageMetadata) SetSize(v int32) {
	o.Size = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *StorageMetadata) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageMetadata) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *StorageMetadata) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *StorageMetadata) SetContentType(v string) {
	o.ContentType = &v
}

// GetLastModified returns the LastModified field value if set, zero value otherwise.
func (o *StorageMetadata) GetLastModified() time.Time {
	if o == nil || IsNil(o.LastModified) {
		var ret time.Time
		return ret
	}
	return *o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageMetadata) GetLastModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastModified) {
		return nil, false
	}
	return o.LastModified, true
}

// HasLastModified returns a boolean if a field has been set.
func (o *StorageMetadata) HasLastModified() bool {
	if o != nil && !IsNil(o.LastModified) {
		return true
	}

	return false
}

// SetLastModified gets a reference to the given time.Time and assigns it to the LastModified field.
func (o *StorageMetadata) SetLastModified(v time.Time) {
	o.LastModified = &v
}

// GetEtag returns the Etag field value if set, zero value otherwise.
func (o *StorageMetadata) GetEtag() string {
	if o == nil || IsNil(o.Etag) {
		var ret string
		return ret
	}
	return *o.Etag
}

// GetEtagOk returns a tuple with the Etag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageMetadata) GetEtagOk() (*string, bool) {
	if o == nil || IsNil(o.Etag) {
		return nil, false
	}
	return o.Etag, true
}

// HasEtag returns a boolean if a field has been set.
func (o *StorageMetadata) HasEtag() bool {
	if o != nil && !IsNil(o.Etag) {
		return true
	}

	return false
}

// SetEtag gets a reference to the given string and assigns it to the Etag field.
func (o *StorageMetadata) SetEtag(v string) {
	o.Etag = &v
}

func (o StorageMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Exists) {
		toSerialize["exists"] = o.Exists
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.ContentType) {
		toSerialize["contentType"] = o.ContentType
	}
	if !IsNil(o.LastModified) {
		toSerialize["lastModified"] = o.LastModified
	}
	if !IsNil(o.Etag) {
		toSerialize["etag"] = o.Etag
	}
	return toSerialize, nil
}

type NullableStorageMetadata struct {
	value *StorageMetadata
	isSet bool
}

func (v NullableStorageMetadata) Get() *StorageMetadata {
	return v.value
}

func (v *NullableStorageMetadata) Set(val *StorageMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageMetadata(val *StorageMetadata) *NullableStorageMetadata {
	return &NullableStorageMetadata{value: val, isSet: true}
}

func (v NullableStorageMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


