/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StorageGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageGetRequest{}

// StorageGetRequest struct for StorageGetRequest
type StorageGetRequest struct {
	Key string `json:"key"`
}

type _StorageGetRequest StorageGetRequest

// NewStorageGetRequest instantiates a new StorageGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageGetRequest(key string) *StorageGetRequest {
	this := StorageGetRequest{}
	this.Key = key
	return &this
}

// NewStorageGetRequestWithDefaults instantiates a new StorageGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageGetRequestWithDefaults() *StorageGetRequest {
	this := StorageGetRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *StorageGetRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *StorageGetRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *StorageGetRequest) SetKey(v string) {
	o.Key = v
}

func (o StorageGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *StorageGetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageGetRequest := _StorageGetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStorageGetRequest)

	if err != nil {
		return err
	}

	*o = StorageGetRequest(varStorageGetRequest)

	return err
}

type NullableStorageGetRequest struct {
	value *StorageGetRequest
	isSet bool
}

func (v NullableStorageGetRequest) Get() *StorageGetRequest {
	return v.value
}

func (v *NullableStorageGetRequest) Set(val *StorageGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageGetRequest(val *StorageGetRequest) *NullableStorageGetRequest {
	return &NullableStorageGetRequest{value: val, isSet: true}
}

func (v NullableStorageGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


