/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the CacheDeleteMany200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheDeleteMany200Response{}

// CacheDeleteMany200Response struct for CacheDeleteMany200Response
type CacheDeleteMany200Response struct {
	Success *bool `json:"success,omitempty"`
	// Number of keys requested for deletion
	Count *int32 `json:"count,omitempty"`
	// Number of keys actually deleted
	Deleted *int32 `json:"deleted,omitempty"`
}

// NewCacheDeleteMany200Response instantiates a new CacheDeleteMany200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheDeleteMany200Response() *CacheDeleteMany200Response {
	this := CacheDeleteMany200Response{}
	return &this
}

// NewCacheDeleteMany200ResponseWithDefaults instantiates a new CacheDeleteMany200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheDeleteMany200ResponseWithDefaults() *CacheDeleteMany200Response {
	this := CacheDeleteMany200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CacheDeleteMany200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheDeleteMany200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CacheDeleteMany200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CacheDeleteMany200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *CacheDeleteMany200Response) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheDeleteMany200Response) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *CacheDeleteMany200Response) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *CacheDeleteMany200Response) SetCount(v int32) {
	o.Count = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *CacheDeleteMany200Response) GetDeleted() int32 {
	if o == nil || IsNil(o.Deleted) {
		var ret int32
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheDeleteMany200Response) GetDeletedOk() (*int32, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *CacheDeleteMany200Response) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given int32 and assigns it to the Deleted field.
func (o *CacheDeleteMany200Response) SetDeleted(v int32) {
	o.Deleted = &v
}

func (o CacheDeleteMany200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheDeleteMany200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	return toSerialize, nil
}

type NullableCacheDeleteMany200Response struct {
	value *CacheDeleteMany200Response
	isSet bool
}

func (v NullableCacheDeleteMany200Response) Get() *CacheDeleteMany200Response {
	return v.value
}

func (v *NullableCacheDeleteMany200Response) Set(val *CacheDeleteMany200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheDeleteMany200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheDeleteMany200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheDeleteMany200Response(val *CacheDeleteMany200Response) *NullableCacheDeleteMany200Response {
	return &NullableCacheDeleteMany200Response{value: val, isSet: true}
}

func (v NullableCacheDeleteMany200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheDeleteMany200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


