/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the TokenUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenUsage{}

// TokenUsage struct for TokenUsage
type TokenUsage struct {
	// Tokens in the prompt
	PromptTokens *int32 `json:"prompt_tokens,omitempty"`
	// Tokens generated
	CompletionTokens *int32 `json:"completion_tokens,omitempty"`
	// Total tokens consumed
	TotalTokens *int32 `json:"total_tokens,omitempty"`
}

// NewTokenUsage instantiates a new TokenUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenUsage() *TokenUsage {
	this := TokenUsage{}
	return &this
}

// NewTokenUsageWithDefaults instantiates a new TokenUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenUsageWithDefaults() *TokenUsage {
	this := TokenUsage{}
	return &this
}

// GetPromptTokens returns the PromptTokens field value if set, zero value otherwise.
func (o *TokenUsage) GetPromptTokens() int32 {
	if o == nil || IsNil(o.PromptTokens) {
		var ret int32
		return ret
	}
	return *o.PromptTokens
}

// GetPromptTokensOk returns a tuple with the PromptTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenUsage) GetPromptTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.PromptTokens) {
		return nil, false
	}
	return o.PromptTokens, true
}

// HasPromptTokens returns a boolean if a field has been set.
func (o *TokenUsage) HasPromptTokens() bool {
	if o != nil && !IsNil(o.PromptTokens) {
		return true
	}

	return false
}

// SetPromptTokens gets a reference to the given int32 and assigns it to the PromptTokens field.
func (o *TokenUsage) SetPromptTokens(v int32) {
	o.PromptTokens = &v
}

// GetCompletionTokens returns the CompletionTokens field value if set, zero value otherwise.
func (o *TokenUsage) GetCompletionTokens() int32 {
	if o == nil || IsNil(o.CompletionTokens) {
		var ret int32
		return ret
	}
	return *o.CompletionTokens
}

// GetCompletionTokensOk returns a tuple with the CompletionTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenUsage) GetCompletionTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.CompletionTokens) {
		return nil, false
	}
	return o.CompletionTokens, true
}

// HasCompletionTokens returns a boolean if a field has been set.
func (o *TokenUsage) HasCompletionTokens() bool {
	if o != nil && !IsNil(o.CompletionTokens) {
		return true
	}

	return false
}

// SetCompletionTokens gets a reference to the given int32 and assigns it to the CompletionTokens field.
func (o *TokenUsage) SetCompletionTokens(v int32) {
	o.CompletionTokens = &v
}

// GetTotalTokens returns the TotalTokens field value if set, zero value otherwise.
func (o *TokenUsage) GetTotalTokens() int32 {
	if o == nil || IsNil(o.TotalTokens) {
		var ret int32
		return ret
	}
	return *o.TotalTokens
}

// GetTotalTokensOk returns a tuple with the TotalTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenUsage) GetTotalTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTokens) {
		return nil, false
	}
	return o.TotalTokens, true
}

// HasTotalTokens returns a boolean if a field has been set.
func (o *TokenUsage) HasTotalTokens() bool {
	if o != nil && !IsNil(o.TotalTokens) {
		return true
	}

	return false
}

// SetTotalTokens gets a reference to the given int32 and assigns it to the TotalTokens field.
func (o *TokenUsage) SetTotalTokens(v int32) {
	o.TotalTokens = &v
}

func (o TokenUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PromptTokens) {
		toSerialize["prompt_tokens"] = o.PromptTokens
	}
	if !IsNil(o.CompletionTokens) {
		toSerialize["completion_tokens"] = o.CompletionTokens
	}
	if !IsNil(o.TotalTokens) {
		toSerialize["total_tokens"] = o.TotalTokens
	}
	return toSerialize, nil
}

type NullableTokenUsage struct {
	value *TokenUsage
	isSet bool
}

func (v NullableTokenUsage) Get() *TokenUsage {
	return v.value
}

func (v *NullableTokenUsage) Set(val *TokenUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenUsage(val *TokenUsage) *NullableTokenUsage {
	return &NullableTokenUsage{value: val, isSet: true}
}

func (v NullableTokenUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


