/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the ServicesInvoke200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesInvoke200Response{}

// ServicesInvoke200Response struct for ServicesInvoke200Response
type ServicesInvoke200Response struct {
	Success *bool `json:"success,omitempty"`
	Result interface{} `json:"result,omitempty"`
}

// NewServicesInvoke200Response instantiates a new ServicesInvoke200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesInvoke200Response() *ServicesInvoke200Response {
	this := ServicesInvoke200Response{}
	return &this
}

// NewServicesInvoke200ResponseWithDefaults instantiates a new ServicesInvoke200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesInvoke200ResponseWithDefaults() *ServicesInvoke200Response {
	this := ServicesInvoke200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ServicesInvoke200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesInvoke200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ServicesInvoke200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ServicesInvoke200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetResult returns the Result field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServicesInvoke200Response) GetResult() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServicesInvoke200Response) GetResultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return &o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ServicesInvoke200Response) HasResult() bool {
	if o != nil && IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given interface{} and assigns it to the Result field.
func (o *ServicesInvoke200Response) SetResult(v interface{}) {
	o.Result = v
}

func (o ServicesInvoke200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesInvoke200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableServicesInvoke200Response struct {
	value *ServicesInvoke200Response
	isSet bool
}

func (v NullableServicesInvoke200Response) Get() *ServicesInvoke200Response {
	return v.value
}

func (v *NullableServicesInvoke200Response) Set(val *ServicesInvoke200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesInvoke200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesInvoke200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesInvoke200Response(val *ServicesInvoke200Response) *NullableServicesInvoke200Response {
	return &NullableServicesInvoke200Response{value: val, isSet: true}
}

func (v NullableServicesInvoke200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesInvoke200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


