/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CacheGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheGetRequest{}

// CacheGetRequest struct for CacheGetRequest
type CacheGetRequest struct {
	Key string `json:"key"`
}

type _CacheGetRequest CacheGetRequest

// NewCacheGetRequest instantiates a new CacheGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheGetRequest(key string) *CacheGetRequest {
	this := CacheGetRequest{}
	this.Key = key
	return &this
}

// NewCacheGetRequestWithDefaults instantiates a new CacheGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheGetRequestWithDefaults() *CacheGetRequest {
	this := CacheGetRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *CacheGetRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CacheGetRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CacheGetRequest) SetKey(v string) {
	o.Key = v
}

func (o CacheGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *CacheGetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCacheGetRequest := _CacheGetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCacheGetRequest)

	if err != nil {
		return err
	}

	*o = CacheGetRequest(varCacheGetRequest)

	return err
}

type NullableCacheGetRequest struct {
	value *CacheGetRequest
	isSet bool
}

func (v NullableCacheGetRequest) Get() *CacheGetRequest {
	return v.value
}

func (v *NullableCacheGetRequest) Set(val *CacheGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheGetRequest(val *CacheGetRequest) *NullableCacheGetRequest {
	return &NullableCacheGetRequest{value: val, isSet: true}
}

func (v NullableCacheGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


