/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthSigninRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthSigninRequest{}

// AuthSigninRequest struct for AuthSigninRequest
type AuthSigninRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
}

type _AuthSigninRequest AuthSigninRequest

// NewAuthSigninRequest instantiates a new AuthSigninRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthSigninRequest(email string, password string) *AuthSigninRequest {
	this := AuthSigninRequest{}
	this.Email = email
	this.Password = password
	return &this
}

// NewAuthSigninRequestWithDefaults instantiates a new AuthSigninRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthSigninRequestWithDefaults() *AuthSigninRequest {
	this := AuthSigninRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *AuthSigninRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AuthSigninRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AuthSigninRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *AuthSigninRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *AuthSigninRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *AuthSigninRequest) SetPassword(v string) {
	o.Password = v
}

func (o AuthSigninRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthSigninRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *AuthSigninRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthSigninRequest := _AuthSigninRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthSigninRequest)

	if err != nil {
		return err
	}

	*o = AuthSigninRequest(varAuthSigninRequest)

	return err
}

type NullableAuthSigninRequest struct {
	value *AuthSigninRequest
	isSet bool
}

func (v NullableAuthSigninRequest) Get() *AuthSigninRequest {
	return v.value
}

func (v *NullableAuthSigninRequest) Set(val *AuthSigninRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthSigninRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthSigninRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthSigninRequest(val *AuthSigninRequest) *NullableAuthSigninRequest {
	return &NullableAuthSigninRequest{value: val, isSet: true}
}

func (v NullableAuthSigninRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthSigninRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


