/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DbBatchRequestQueriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DbBatchRequestQueriesInner{}

// DbBatchRequestQueriesInner struct for DbBatchRequestQueriesInner
type DbBatchRequestQueriesInner struct {
	// SQL query to execute
	Sql string `json:"sql"`
	Params []interface{} `json:"params,omitempty"`
}

type _DbBatchRequestQueriesInner DbBatchRequestQueriesInner

// NewDbBatchRequestQueriesInner instantiates a new DbBatchRequestQueriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbBatchRequestQueriesInner(sql string) *DbBatchRequestQueriesInner {
	this := DbBatchRequestQueriesInner{}
	this.Sql = sql
	return &this
}

// NewDbBatchRequestQueriesInnerWithDefaults instantiates a new DbBatchRequestQueriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbBatchRequestQueriesInnerWithDefaults() *DbBatchRequestQueriesInner {
	this := DbBatchRequestQueriesInner{}
	return &this
}

// GetSql returns the Sql field value
func (o *DbBatchRequestQueriesInner) GetSql() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sql
}

// GetSqlOk returns a tuple with the Sql field value
// and a boolean to check if the value has been set.
func (o *DbBatchRequestQueriesInner) GetSqlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sql, true
}

// SetSql sets field value
func (o *DbBatchRequestQueriesInner) SetSql(v string) {
	o.Sql = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *DbBatchRequestQueriesInner) GetParams() []interface{} {
	if o == nil || IsNil(o.Params) {
		var ret []interface{}
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DbBatchRequestQueriesInner) GetParamsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *DbBatchRequestQueriesInner) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given []interface{} and assigns it to the Params field.
func (o *DbBatchRequestQueriesInner) SetParams(v []interface{}) {
	o.Params = v
}

func (o DbBatchRequestQueriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DbBatchRequestQueriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sql"] = o.Sql
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	return toSerialize, nil
}

func (o *DbBatchRequestQueriesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sql",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDbBatchRequestQueriesInner := _DbBatchRequestQueriesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDbBatchRequestQueriesInner)

	if err != nil {
		return err
	}

	*o = DbBatchRequestQueriesInner(varDbBatchRequestQueriesInner)

	return err
}

type NullableDbBatchRequestQueriesInner struct {
	value *DbBatchRequestQueriesInner
	isSet bool
}

func (v NullableDbBatchRequestQueriesInner) Get() *DbBatchRequestQueriesInner {
	return v.value
}

func (v *NullableDbBatchRequestQueriesInner) Set(val *DbBatchRequestQueriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDbBatchRequestQueriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDbBatchRequestQueriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbBatchRequestQueriesInner(val *DbBatchRequestQueriesInner) *NullableDbBatchRequestQueriesInner {
	return &NullableDbBatchRequestQueriesInner{value: val, isSet: true}
}

func (v NullableDbBatchRequestQueriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbBatchRequestQueriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


