/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CacheDeleteManyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheDeleteManyRequest{}

// CacheDeleteManyRequest struct for CacheDeleteManyRequest
type CacheDeleteManyRequest struct {
	// Keys to delete (max 500)
	Keys []string `json:"keys"`
}

type _CacheDeleteManyRequest CacheDeleteManyRequest

// NewCacheDeleteManyRequest instantiates a new CacheDeleteManyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheDeleteManyRequest(keys []string) *CacheDeleteManyRequest {
	this := CacheDeleteManyRequest{}
	this.Keys = keys
	return &this
}

// NewCacheDeleteManyRequestWithDefaults instantiates a new CacheDeleteManyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheDeleteManyRequestWithDefaults() *CacheDeleteManyRequest {
	this := CacheDeleteManyRequest{}
	return &this
}

// GetKeys returns the Keys field value
func (o *CacheDeleteManyRequest) GetKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *CacheDeleteManyRequest) GetKeysOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *CacheDeleteManyRequest) SetKeys(v []string) {
	o.Keys = v
}

func (o CacheDeleteManyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheDeleteManyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keys"] = o.Keys
	return toSerialize, nil
}

func (o *CacheDeleteManyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCacheDeleteManyRequest := _CacheDeleteManyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCacheDeleteManyRequest)

	if err != nil {
		return err
	}

	*o = CacheDeleteManyRequest(varCacheDeleteManyRequest)

	return err
}

type NullableCacheDeleteManyRequest struct {
	value *CacheDeleteManyRequest
	isSet bool
}

func (v NullableCacheDeleteManyRequest) Get() *CacheDeleteManyRequest {
	return v.value
}

func (v *NullableCacheDeleteManyRequest) Set(val *CacheDeleteManyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheDeleteManyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheDeleteManyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheDeleteManyRequest(val *CacheDeleteManyRequest) *NullableCacheDeleteManyRequest {
	return &NullableCacheDeleteManyRequest{value: val, isSet: true}
}

func (v NullableCacheDeleteManyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheDeleteManyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


