/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GatewayBillingLogRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayBillingLogRequest{}

// GatewayBillingLogRequest struct for GatewayBillingLogRequest
type GatewayBillingLogRequest struct {
	// The Consumer ID making the request
	ConsumerId string `json:"consumerId"`
	// The Developer Gateway API ID being consumed
	ApiId string `json:"apiId"`
	// Optional metric name (default: 'units')
	Metric *string `json:"metric,omitempty"`
	// Amount of usage to log
	Units int32 `json:"units"`
}

type _GatewayBillingLogRequest GatewayBillingLogRequest

// NewGatewayBillingLogRequest instantiates a new GatewayBillingLogRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayBillingLogRequest(consumerId string, apiId string, units int32) *GatewayBillingLogRequest {
	this := GatewayBillingLogRequest{}
	this.ConsumerId = consumerId
	this.ApiId = apiId
	this.Units = units
	return &this
}

// NewGatewayBillingLogRequestWithDefaults instantiates a new GatewayBillingLogRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayBillingLogRequestWithDefaults() *GatewayBillingLogRequest {
	this := GatewayBillingLogRequest{}
	return &this
}

// GetConsumerId returns the ConsumerId field value
func (o *GatewayBillingLogRequest) GetConsumerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConsumerId
}

// GetConsumerIdOk returns a tuple with the ConsumerId field value
// and a boolean to check if the value has been set.
func (o *GatewayBillingLogRequest) GetConsumerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsumerId, true
}

// SetConsumerId sets field value
func (o *GatewayBillingLogRequest) SetConsumerId(v string) {
	o.ConsumerId = v
}

// GetApiId returns the ApiId field value
func (o *GatewayBillingLogRequest) GetApiId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiId
}

// GetApiIdOk returns a tuple with the ApiId field value
// and a boolean to check if the value has been set.
func (o *GatewayBillingLogRequest) GetApiIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiId, true
}

// SetApiId sets field value
func (o *GatewayBillingLogRequest) SetApiId(v string) {
	o.ApiId = v
}

// GetMetric returns the Metric field value if set, zero value otherwise.
func (o *GatewayBillingLogRequest) GetMetric() string {
	if o == nil || IsNil(o.Metric) {
		var ret string
		return ret
	}
	return *o.Metric
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayBillingLogRequest) GetMetricOk() (*string, bool) {
	if o == nil || IsNil(o.Metric) {
		return nil, false
	}
	return o.Metric, true
}

// HasMetric returns a boolean if a field has been set.
func (o *GatewayBillingLogRequest) HasMetric() bool {
	if o != nil && !IsNil(o.Metric) {
		return true
	}

	return false
}

// SetMetric gets a reference to the given string and assigns it to the Metric field.
func (o *GatewayBillingLogRequest) SetMetric(v string) {
	o.Metric = &v
}

// GetUnits returns the Units field value
func (o *GatewayBillingLogRequest) GetUnits() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Units
}

// GetUnitsOk returns a tuple with the Units field value
// and a boolean to check if the value has been set.
func (o *GatewayBillingLogRequest) GetUnitsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Units, true
}

// SetUnits sets field value
func (o *GatewayBillingLogRequest) SetUnits(v int32) {
	o.Units = v
}

func (o GatewayBillingLogRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayBillingLogRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["consumerId"] = o.ConsumerId
	toSerialize["apiId"] = o.ApiId
	if !IsNil(o.Metric) {
		toSerialize["metric"] = o.Metric
	}
	toSerialize["units"] = o.Units
	return toSerialize, nil
}

func (o *GatewayBillingLogRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"consumerId",
		"apiId",
		"units",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayBillingLogRequest := _GatewayBillingLogRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayBillingLogRequest)

	if err != nil {
		return err
	}

	*o = GatewayBillingLogRequest(varGatewayBillingLogRequest)

	return err
}

type NullableGatewayBillingLogRequest struct {
	value *GatewayBillingLogRequest
	isSet bool
}

func (v NullableGatewayBillingLogRequest) Get() *GatewayBillingLogRequest {
	return v.value
}

func (v *NullableGatewayBillingLogRequest) Set(val *GatewayBillingLogRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayBillingLogRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayBillingLogRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayBillingLogRequest(val *GatewayBillingLogRequest) *NullableGatewayBillingLogRequest {
	return &NullableGatewayBillingLogRequest{value: val, isSet: true}
}

func (v NullableGatewayBillingLogRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayBillingLogRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


