/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the TypeStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypeStats{}

// TypeStats struct for TypeStats
type TypeStats struct {
	Type *string `json:"type,omitempty"`
	Count *int32 `json:"count,omitempty"`
}

// NewTypeStats instantiates a new TypeStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypeStats() *TypeStats {
	this := TypeStats{}
	return &this
}

// NewTypeStatsWithDefaults instantiates a new TypeStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypeStatsWithDefaults() *TypeStats {
	this := TypeStats{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TypeStats) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypeStats) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TypeStats) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TypeStats) SetType(v string) {
	o.Type = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *TypeStats) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypeStats) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *TypeStats) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *TypeStats) SetCount(v int32) {
	o.Count = &v
}

func (o TypeStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypeStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableTypeStats struct {
	value *TypeStats
	isSet bool
}

func (v NullableTypeStats) Get() *TypeStats {
	return v.value
}

func (v *NullableTypeStats) Set(val *TypeStats) {
	v.value = val
	v.isSet = true
}

func (v NullableTypeStats) IsSet() bool {
	return v.isSet
}

func (v *NullableTypeStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypeStats(val *TypeStats) *NullableTypeStats {
	return &NullableTypeStats{value: val, isSet: true}
}

func (v NullableTypeStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypeStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


