/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchGetRequest{}

// SearchGetRequest struct for SearchGetRequest
type SearchGetRequest struct {
	// ID of the item to retrieve
	Id string `json:"id"`
}

type _SearchGetRequest SearchGetRequest

// NewSearchGetRequest instantiates a new SearchGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchGetRequest(id string) *SearchGetRequest {
	this := SearchGetRequest{}
	this.Id = id
	return &this
}

// NewSearchGetRequestWithDefaults instantiates a new SearchGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchGetRequestWithDefaults() *SearchGetRequest {
	this := SearchGetRequest{}
	return &this
}

// GetId returns the Id field value
func (o *SearchGetRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SearchGetRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SearchGetRequest) SetId(v string) {
	o.Id = v
}

func (o SearchGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *SearchGetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchGetRequest := _SearchGetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchGetRequest)

	if err != nil {
		return err
	}

	*o = SearchGetRequest(varSearchGetRequest)

	return err
}

type NullableSearchGetRequest struct {
	value *SearchGetRequest
	isSet bool
}

func (v NullableSearchGetRequest) Get() *SearchGetRequest {
	return v.value
}

func (v *NullableSearchGetRequest) Set(val *SearchGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchGetRequest(val *SearchGetRequest) *NullableSearchGetRequest {
	return &NullableSearchGetRequest{value: val, isSet: true}
}

func (v NullableSearchGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


