/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the Query200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Query200Response{}

// Query200Response struct for Query200Response
type Query200Response struct {
	Results []SearchResult `json:"results,omitempty"`
}

// NewQuery200Response instantiates a new Query200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuery200Response() *Query200Response {
	this := Query200Response{}
	return &this
}

// NewQuery200ResponseWithDefaults instantiates a new Query200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuery200ResponseWithDefaults() *Query200Response {
	this := Query200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *Query200Response) GetResults() []SearchResult {
	if o == nil || IsNil(o.Results) {
		var ret []SearchResult
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query200Response) GetResultsOk() ([]SearchResult, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *Query200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []SearchResult and assigns it to the Results field.
func (o *Query200Response) SetResults(v []SearchResult) {
	o.Results = v
}

func (o Query200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Query200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableQuery200Response struct {
	value *Query200Response
	isSet bool
}

func (v NullableQuery200Response) Get() *Query200Response {
	return v.value
}

func (v *NullableQuery200Response) Set(val *Query200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQuery200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQuery200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuery200Response(val *Query200Response) *NullableQuery200Response {
	return &NullableQuery200Response{value: val, isSet: true}
}

func (v NullableQuery200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuery200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


