/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the CacheKeys200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheKeys200Response{}

// CacheKeys200Response struct for CacheKeys200Response
type CacheKeys200Response struct {
	Keys []string `json:"keys,omitempty"`
	// True if the result was capped at 10,000 keys
	Truncated *bool `json:"truncated,omitempty"`
}

// NewCacheKeys200Response instantiates a new CacheKeys200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheKeys200Response() *CacheKeys200Response {
	this := CacheKeys200Response{}
	return &this
}

// NewCacheKeys200ResponseWithDefaults instantiates a new CacheKeys200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheKeys200ResponseWithDefaults() *CacheKeys200Response {
	this := CacheKeys200Response{}
	return &this
}

// GetKeys returns the Keys field value if set, zero value otherwise.
func (o *CacheKeys200Response) GetKeys() []string {
	if o == nil || IsNil(o.Keys) {
		var ret []string
		return ret
	}
	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheKeys200Response) GetKeysOk() ([]string, bool) {
	if o == nil || IsNil(o.Keys) {
		return nil, false
	}
	return o.Keys, true
}

// HasKeys returns a boolean if a field has been set.
func (o *CacheKeys200Response) HasKeys() bool {
	if o != nil && !IsNil(o.Keys) {
		return true
	}

	return false
}

// SetKeys gets a reference to the given []string and assigns it to the Keys field.
func (o *CacheKeys200Response) SetKeys(v []string) {
	o.Keys = v
}

// GetTruncated returns the Truncated field value if set, zero value otherwise.
func (o *CacheKeys200Response) GetTruncated() bool {
	if o == nil || IsNil(o.Truncated) {
		var ret bool
		return ret
	}
	return *o.Truncated
}

// GetTruncatedOk returns a tuple with the Truncated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheKeys200Response) GetTruncatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Truncated) {
		return nil, false
	}
	return o.Truncated, true
}

// HasTruncated returns a boolean if a field has been set.
func (o *CacheKeys200Response) HasTruncated() bool {
	if o != nil && !IsNil(o.Truncated) {
		return true
	}

	return false
}

// SetTruncated gets a reference to the given bool and assigns it to the Truncated field.
func (o *CacheKeys200Response) SetTruncated(v bool) {
	o.Truncated = &v
}

func (o CacheKeys200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheKeys200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Keys) {
		toSerialize["keys"] = o.Keys
	}
	if !IsNil(o.Truncated) {
		toSerialize["truncated"] = o.Truncated
	}
	return toSerialize, nil
}

type NullableCacheKeys200Response struct {
	value *CacheKeys200Response
	isSet bool
}

func (v NullableCacheKeys200Response) Get() *CacheKeys200Response {
	return v.value
}

func (v *NullableCacheKeys200Response) Set(val *CacheKeys200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheKeys200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheKeys200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheKeys200Response(val *CacheKeys200Response) *NullableCacheKeys200Response {
	return &NullableCacheKeys200Response{value: val, isSet: true}
}

func (v NullableCacheKeys200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheKeys200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


