/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the SearchGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchGet200Response{}

// SearchGet200Response struct for SearchGet200Response
type SearchGet200Response struct {
	Result NullableSearchResult `json:"result,omitempty"`
	Exists *bool `json:"exists,omitempty"`
}

// NewSearchGet200Response instantiates a new SearchGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchGet200Response() *SearchGet200Response {
	this := SearchGet200Response{}
	return &this
}

// NewSearchGet200ResponseWithDefaults instantiates a new SearchGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchGet200ResponseWithDefaults() *SearchGet200Response {
	this := SearchGet200Response{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchGet200Response) GetResult() SearchResult {
	if o == nil || IsNil(o.Result.Get()) {
		var ret SearchResult
		return ret
	}
	return *o.Result.Get()
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchGet200Response) GetResultOk() (*SearchResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result.Get(), o.Result.IsSet()
}

// HasResult returns a boolean if a field has been set.
func (o *SearchGet200Response) HasResult() bool {
	if o != nil && o.Result.IsSet() {
		return true
	}

	return false
}

// SetResult gets a reference to the given NullableSearchResult and assigns it to the Result field.
func (o *SearchGet200Response) SetResult(v SearchResult) {
	o.Result.Set(&v)
}
// SetResultNil sets the value for Result to be an explicit nil
func (o *SearchGet200Response) SetResultNil() {
	o.Result.Set(nil)
}

// UnsetResult ensures that no value is present for Result, not even an explicit nil
func (o *SearchGet200Response) UnsetResult() {
	o.Result.Unset()
}

// GetExists returns the Exists field value if set, zero value otherwise.
func (o *SearchGet200Response) GetExists() bool {
	if o == nil || IsNil(o.Exists) {
		var ret bool
		return ret
	}
	return *o.Exists
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchGet200Response) GetExistsOk() (*bool, bool) {
	if o == nil || IsNil(o.Exists) {
		return nil, false
	}
	return o.Exists, true
}

// HasExists returns a boolean if a field has been set.
func (o *SearchGet200Response) HasExists() bool {
	if o != nil && !IsNil(o.Exists) {
		return true
	}

	return false
}

// SetExists gets a reference to the given bool and assigns it to the Exists field.
func (o *SearchGet200Response) SetExists(v bool) {
	o.Exists = &v
}

func (o SearchGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Result.IsSet() {
		toSerialize["result"] = o.Result.Get()
	}
	if !IsNil(o.Exists) {
		toSerialize["exists"] = o.Exists
	}
	return toSerialize, nil
}

type NullableSearchGet200Response struct {
	value *SearchGet200Response
	isSet bool
}

func (v NullableSearchGet200Response) Get() *SearchGet200Response {
	return v.value
}

func (v *NullableSearchGet200Response) Set(val *SearchGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchGet200Response(val *SearchGet200Response) *NullableSearchGet200Response {
	return &NullableSearchGet200Response{value: val, isSet: true}
}

func (v NullableSearchGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


