/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the StorageCopy200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageCopy200Response{}

// StorageCopy200Response struct for StorageCopy200Response
type StorageCopy200Response struct {
	Success *bool `json:"success,omitempty"`
	// CDN URL of the new file
	Url *string `json:"url,omitempty"`
}

// NewStorageCopy200Response instantiates a new StorageCopy200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageCopy200Response() *StorageCopy200Response {
	this := StorageCopy200Response{}
	return &this
}

// NewStorageCopy200ResponseWithDefaults instantiates a new StorageCopy200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageCopy200ResponseWithDefaults() *StorageCopy200Response {
	this := StorageCopy200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *StorageCopy200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageCopy200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *StorageCopy200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *StorageCopy200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *StorageCopy200Response) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageCopy200Response) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *StorageCopy200Response) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *StorageCopy200Response) SetUrl(v string) {
	o.Url = &v
}

func (o StorageCopy200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageCopy200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableStorageCopy200Response struct {
	value *StorageCopy200Response
	isSet bool
}

func (v NullableStorageCopy200Response) Get() *StorageCopy200Response {
	return v.value
}

func (v *NullableStorageCopy200Response) Set(val *StorageCopy200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageCopy200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageCopy200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageCopy200Response(val *StorageCopy200Response) *NullableStorageCopy200Response {
	return &NullableStorageCopy200Response{value: val, isSet: true}
}

func (v NullableStorageCopy200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageCopy200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


