/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryRequest{}

// QueryRequest struct for QueryRequest
type QueryRequest struct {
	Text string `json:"text"`
	TopK *int32 `json:"topK,omitempty"`
	Types []string `json:"types,omitempty"`
	Filter map[string]interface{} `json:"filter,omitempty"`
}

type _QueryRequest QueryRequest

// NewQueryRequest instantiates a new QueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryRequest(text string) *QueryRequest {
	this := QueryRequest{}
	this.Text = text
	var topK int32 = 5
	this.TopK = &topK
	return &this
}

// NewQueryRequestWithDefaults instantiates a new QueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryRequestWithDefaults() *QueryRequest {
	this := QueryRequest{}
	var topK int32 = 5
	this.TopK = &topK
	return &this
}

// GetText returns the Text field value
func (o *QueryRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *QueryRequest) SetText(v string) {
	o.Text = v
}

// GetTopK returns the TopK field value if set, zero value otherwise.
func (o *QueryRequest) GetTopK() int32 {
	if o == nil || IsNil(o.TopK) {
		var ret int32
		return ret
	}
	return *o.TopK
}

// GetTopKOk returns a tuple with the TopK field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetTopKOk() (*int32, bool) {
	if o == nil || IsNil(o.TopK) {
		return nil, false
	}
	return o.TopK, true
}

// HasTopK returns a boolean if a field has been set.
func (o *QueryRequest) HasTopK() bool {
	if o != nil && !IsNil(o.TopK) {
		return true
	}

	return false
}

// SetTopK gets a reference to the given int32 and assigns it to the TopK field.
func (o *QueryRequest) SetTopK(v int32) {
	o.TopK = &v
}

// GetTypes returns the Types field value if set, zero value otherwise.
func (o *QueryRequest) GetTypes() []string {
	if o == nil || IsNil(o.Types) {
		var ret []string
		return ret
	}
	return o.Types
}

// GetTypesOk returns a tuple with the Types field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryRequest) GetTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.Types) {
		return nil, false
	}
	return o.Types, true
}

// HasTypes returns a boolean if a field has been set.
func (o *QueryRequest) HasTypes() bool {
	if o != nil && !IsNil(o.Types) {
		return true
	}

	return false
}

// SetTypes gets a reference to the given []string and assigns it to the Types field.
func (o *QueryRequest) SetTypes(v []string) {
	o.Types = v
}

// GetFilter returns the Filter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QueryRequest) GetFilter() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QueryRequest) GetFilterOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return &o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *QueryRequest) HasFilter() bool {
	if o != nil && IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given map[string]interface{} and assigns it to the Filter field.
func (o *QueryRequest) SetFilter(v map[string]interface{}) {
	o.Filter = v
}

func (o QueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	if !IsNil(o.TopK) {
		toSerialize["topK"] = o.TopK
	}
	if !IsNil(o.Types) {
		toSerialize["types"] = o.Types
	}
	if o.Filter != nil {
		toSerialize["filter"] = o.Filter
	}
	return toSerialize, nil
}

func (o *QueryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryRequest := _QueryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryRequest)

	if err != nil {
		return err
	}

	*o = QueryRequest(varQueryRequest)

	return err
}

type NullableQueryRequest struct {
	value *QueryRequest
	isSet bool
}

func (v NullableQueryRequest) Get() *QueryRequest {
	return v.value
}

func (v *NullableQueryRequest) Set(val *QueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryRequest(val *QueryRequest) *NullableQueryRequest {
	return &NullableQueryRequest{value: val, isSet: true}
}

func (v NullableQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


