/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServicesInvokeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesInvokeRequest{}

// ServicesInvokeRequest struct for ServicesInvokeRequest
type ServicesInvokeRequest struct {
	ServiceName string `json:"serviceName"`
	Data map[string]interface{} `json:"data"`
}

type _ServicesInvokeRequest ServicesInvokeRequest

// NewServicesInvokeRequest instantiates a new ServicesInvokeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesInvokeRequest(serviceName string, data map[string]interface{}) *ServicesInvokeRequest {
	this := ServicesInvokeRequest{}
	this.ServiceName = serviceName
	this.Data = data
	return &this
}

// NewServicesInvokeRequestWithDefaults instantiates a new ServicesInvokeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesInvokeRequestWithDefaults() *ServicesInvokeRequest {
	this := ServicesInvokeRequest{}
	return &this
}

// GetServiceName returns the ServiceName field value
func (o *ServicesInvokeRequest) GetServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value
// and a boolean to check if the value has been set.
func (o *ServicesInvokeRequest) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceName, true
}

// SetServiceName sets field value
func (o *ServicesInvokeRequest) SetServiceName(v string) {
	o.ServiceName = v
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *ServicesInvokeRequest) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServicesInvokeRequest) GetDataOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ServicesInvokeRequest) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o ServicesInvokeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesInvokeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["serviceName"] = o.ServiceName
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *ServicesInvokeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"serviceName",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServicesInvokeRequest := _ServicesInvokeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServicesInvokeRequest)

	if err != nil {
		return err
	}

	*o = ServicesInvokeRequest(varServicesInvokeRequest)

	return err
}

type NullableServicesInvokeRequest struct {
	value *ServicesInvokeRequest
	isSet bool
}

func (v NullableServicesInvokeRequest) Get() *ServicesInvokeRequest {
	return v.value
}

func (v *NullableServicesInvokeRequest) Set(val *ServicesInvokeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesInvokeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesInvokeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesInvokeRequest(val *ServicesInvokeRequest) *NullableServicesInvokeRequest {
	return &NullableServicesInvokeRequest{value: val, isSet: true}
}

func (v NullableServicesInvokeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesInvokeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


