/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the QueueListJobs200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueListJobs200Response{}

// QueueListJobs200Response struct for QueueListJobs200Response
type QueueListJobs200Response struct {
	Jobs []JobRecord `json:"jobs,omitempty"`
	ListComplete *bool `json:"list_complete,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
}

// NewQueueListJobs200Response instantiates a new QueueListJobs200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueListJobs200Response() *QueueListJobs200Response {
	this := QueueListJobs200Response{}
	return &this
}

// NewQueueListJobs200ResponseWithDefaults instantiates a new QueueListJobs200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueListJobs200ResponseWithDefaults() *QueueListJobs200Response {
	this := QueueListJobs200Response{}
	return &this
}

// GetJobs returns the Jobs field value if set, zero value otherwise.
func (o *QueueListJobs200Response) GetJobs() []JobRecord {
	if o == nil || IsNil(o.Jobs) {
		var ret []JobRecord
		return ret
	}
	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueListJobs200Response) GetJobsOk() ([]JobRecord, bool) {
	if o == nil || IsNil(o.Jobs) {
		return nil, false
	}
	return o.Jobs, true
}

// HasJobs returns a boolean if a field has been set.
func (o *QueueListJobs200Response) HasJobs() bool {
	if o != nil && !IsNil(o.Jobs) {
		return true
	}

	return false
}

// SetJobs gets a reference to the given []JobRecord and assigns it to the Jobs field.
func (o *QueueListJobs200Response) SetJobs(v []JobRecord) {
	o.Jobs = v
}

// GetListComplete returns the ListComplete field value if set, zero value otherwise.
func (o *QueueListJobs200Response) GetListComplete() bool {
	if o == nil || IsNil(o.ListComplete) {
		var ret bool
		return ret
	}
	return *o.ListComplete
}

// GetListCompleteOk returns a tuple with the ListComplete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueListJobs200Response) GetListCompleteOk() (*bool, bool) {
	if o == nil || IsNil(o.ListComplete) {
		return nil, false
	}
	return o.ListComplete, true
}

// HasListComplete returns a boolean if a field has been set.
func (o *QueueListJobs200Response) HasListComplete() bool {
	if o != nil && !IsNil(o.ListComplete) {
		return true
	}

	return false
}

// SetListComplete gets a reference to the given bool and assigns it to the ListComplete field.
func (o *QueueListJobs200Response) SetListComplete(v bool) {
	o.ListComplete = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *QueueListJobs200Response) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueListJobs200Response) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *QueueListJobs200Response) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *QueueListJobs200Response) SetCursor(v string) {
	o.Cursor = &v
}

func (o QueueListJobs200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueListJobs200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Jobs) {
		toSerialize["jobs"] = o.Jobs
	}
	if !IsNil(o.ListComplete) {
		toSerialize["list_complete"] = o.ListComplete
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return toSerialize, nil
}

type NullableQueueListJobs200Response struct {
	value *QueueListJobs200Response
	isSet bool
}

func (v NullableQueueListJobs200Response) Get() *QueueListJobs200Response {
	return v.value
}

func (v *NullableQueueListJobs200Response) Set(val *QueueListJobs200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueListJobs200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueListJobs200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueListJobs200Response(val *QueueListJobs200Response) *NullableQueueListJobs200Response {
	return &NullableQueueListJobs200Response{value: val, isSet: true}
}

func (v NullableQueueListJobs200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueListJobs200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


