/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueueGetJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueGetJobRequest{}

// QueueGetJobRequest struct for QueueGetJobRequest
type QueueGetJobRequest struct {
	JobId string `json:"jobId"`
}

type _QueueGetJobRequest QueueGetJobRequest

// NewQueueGetJobRequest instantiates a new QueueGetJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueGetJobRequest(jobId string) *QueueGetJobRequest {
	this := QueueGetJobRequest{}
	this.JobId = jobId
	return &this
}

// NewQueueGetJobRequestWithDefaults instantiates a new QueueGetJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueGetJobRequestWithDefaults() *QueueGetJobRequest {
	this := QueueGetJobRequest{}
	return &this
}

// GetJobId returns the JobId field value
func (o *QueueGetJobRequest) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *QueueGetJobRequest) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *QueueGetJobRequest) SetJobId(v string) {
	o.JobId = v
}

func (o QueueGetJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueGetJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobId"] = o.JobId
	return toSerialize, nil
}

func (o *QueueGetJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueueGetJobRequest := _QueueGetJobRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueueGetJobRequest)

	if err != nil {
		return err
	}

	*o = QueueGetJobRequest(varQueueGetJobRequest)

	return err
}

type NullableQueueGetJobRequest struct {
	value *QueueGetJobRequest
	isSet bool
}

func (v NullableQueueGetJobRequest) Get() *QueueGetJobRequest {
	return v.value
}

func (v *NullableQueueGetJobRequest) Set(val *QueueGetJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueGetJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueGetJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueGetJobRequest(val *QueueGetJobRequest) *NullableQueueGetJobRequest {
	return &NullableQueueGetJobRequest{value: val, isSet: true}
}

func (v NullableQueueGetJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueGetJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


