/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the TokenWallet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenWallet{}

// TokenWallet struct for TokenWallet
type TokenWallet struct {
	// Remaining token balance
	Balance *float32 `json:"balance,omitempty"`
	// Total tokens consumed to date
	TotalConsumed *float32 `json:"total_consumed,omitempty"`
}

// NewTokenWallet instantiates a new TokenWallet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenWallet() *TokenWallet {
	this := TokenWallet{}
	return &this
}

// NewTokenWalletWithDefaults instantiates a new TokenWallet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenWalletWithDefaults() *TokenWallet {
	this := TokenWallet{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *TokenWallet) GetBalance() float32 {
	if o == nil || IsNil(o.Balance) {
		var ret float32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenWallet) GetBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *TokenWallet) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given float32 and assigns it to the Balance field.
func (o *TokenWallet) SetBalance(v float32) {
	o.Balance = &v
}

// GetTotalConsumed returns the TotalConsumed field value if set, zero value otherwise.
func (o *TokenWallet) GetTotalConsumed() float32 {
	if o == nil || IsNil(o.TotalConsumed) {
		var ret float32
		return ret
	}
	return *o.TotalConsumed
}

// GetTotalConsumedOk returns a tuple with the TotalConsumed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenWallet) GetTotalConsumedOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalConsumed) {
		return nil, false
	}
	return o.TotalConsumed, true
}

// HasTotalConsumed returns a boolean if a field has been set.
func (o *TokenWallet) HasTotalConsumed() bool {
	if o != nil && !IsNil(o.TotalConsumed) {
		return true
	}

	return false
}

// SetTotalConsumed gets a reference to the given float32 and assigns it to the TotalConsumed field.
func (o *TokenWallet) SetTotalConsumed(v float32) {
	o.TotalConsumed = &v
}

func (o TokenWallet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenWallet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.TotalConsumed) {
		toSerialize["total_consumed"] = o.TotalConsumed
	}
	return toSerialize, nil
}

type NullableTokenWallet struct {
	value *TokenWallet
	isSet bool
}

func (v NullableTokenWallet) Get() *TokenWallet {
	return v.value
}

func (v *NullableTokenWallet) Set(val *TokenWallet) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenWallet) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenWallet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenWallet(val *TokenWallet) *NullableTokenWallet {
	return &NullableTokenWallet{value: val, isSet: true}
}

func (v NullableTokenWallet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenWallet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


