/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the CacheFlush200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheFlush200Response{}

// CacheFlush200Response struct for CacheFlush200Response
type CacheFlush200Response struct {
	Success *bool `json:"success,omitempty"`
	// Number of keys deleted
	Deleted *int32 `json:"deleted,omitempty"`
}

// NewCacheFlush200Response instantiates a new CacheFlush200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheFlush200Response() *CacheFlush200Response {
	this := CacheFlush200Response{}
	return &this
}

// NewCacheFlush200ResponseWithDefaults instantiates a new CacheFlush200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheFlush200ResponseWithDefaults() *CacheFlush200Response {
	this := CacheFlush200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CacheFlush200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheFlush200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CacheFlush200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CacheFlush200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *CacheFlush200Response) GetDeleted() int32 {
	if o == nil || IsNil(o.Deleted) {
		var ret int32
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheFlush200Response) GetDeletedOk() (*int32, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *CacheFlush200Response) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given int32 and assigns it to the Deleted field.
func (o *CacheFlush200Response) SetDeleted(v int32) {
	o.Deleted = &v
}

func (o CacheFlush200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheFlush200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	return toSerialize, nil
}

type NullableCacheFlush200Response struct {
	value *CacheFlush200Response
	isSet bool
}

func (v NullableCacheFlush200Response) Get() *CacheFlush200Response {
	return v.value
}

func (v *NullableCacheFlush200Response) Set(val *CacheFlush200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheFlush200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheFlush200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheFlush200Response(val *CacheFlush200Response) *NullableCacheFlush200Response {
	return &NullableCacheFlush200Response{value: val, isSet: true}
}

func (v NullableCacheFlush200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheFlush200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


