/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the CacheGetMany200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheGetMany200Response{}

// CacheGetMany200Response struct for CacheGetMany200Response
type CacheGetMany200Response struct {
	Results []CacheGetManyEntry `json:"results,omitempty"`
}

// NewCacheGetMany200Response instantiates a new CacheGetMany200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheGetMany200Response() *CacheGetMany200Response {
	this := CacheGetMany200Response{}
	return &this
}

// NewCacheGetMany200ResponseWithDefaults instantiates a new CacheGetMany200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheGetMany200ResponseWithDefaults() *CacheGetMany200Response {
	this := CacheGetMany200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *CacheGetMany200Response) GetResults() []CacheGetManyEntry {
	if o == nil || IsNil(o.Results) {
		var ret []CacheGetManyEntry
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheGetMany200Response) GetResultsOk() ([]CacheGetManyEntry, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *CacheGetMany200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []CacheGetManyEntry and assigns it to the Results field.
func (o *CacheGetMany200Response) SetResults(v []CacheGetManyEntry) {
	o.Results = v
}

func (o CacheGetMany200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheGetMany200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableCacheGetMany200Response struct {
	value *CacheGetMany200Response
	isSet bool
}

func (v NullableCacheGetMany200Response) Get() *CacheGetMany200Response {
	return v.value
}

func (v *NullableCacheGetMany200Response) Set(val *CacheGetMany200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheGetMany200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheGetMany200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheGetMany200Response(val *CacheGetMany200Response) *NullableCacheGetMany200Response {
	return &NullableCacheGetMany200Response{value: val, isSet: true}
}

func (v NullableCacheGetMany200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheGetMany200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


