/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the CacheListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheListRequest{}

// CacheListRequest struct for CacheListRequest
type CacheListRequest struct {
	// Key prefix to filter by (e.g. \"users:\")
	Prefix *string `json:"prefix,omitempty"`
	// Max keys to return per page (default 100, max 1000)
	Limit *int32 `json:"limit,omitempty"`
	// Pagination cursor from previous response
	Cursor *string `json:"cursor,omitempty"`
}

// NewCacheListRequest instantiates a new CacheListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheListRequest() *CacheListRequest {
	this := CacheListRequest{}
	var limit int32 = 100
	this.Limit = &limit
	return &this
}

// NewCacheListRequestWithDefaults instantiates a new CacheListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheListRequestWithDefaults() *CacheListRequest {
	this := CacheListRequest{}
	var limit int32 = 100
	this.Limit = &limit
	return &this
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *CacheListRequest) GetPrefix() string {
	if o == nil || IsNil(o.Prefix) {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheListRequest) GetPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *CacheListRequest) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *CacheListRequest) SetPrefix(v string) {
	o.Prefix = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *CacheListRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheListRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *CacheListRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *CacheListRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *CacheListRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheListRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *CacheListRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *CacheListRequest) SetCursor(v string) {
	o.Cursor = &v
}

func (o CacheListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return toSerialize, nil
}

type NullableCacheListRequest struct {
	value *CacheListRequest
	isSet bool
}

func (v NullableCacheListRequest) Get() *CacheListRequest {
	return v.value
}

func (v *NullableCacheListRequest) Set(val *CacheListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheListRequest(val *CacheListRequest) *NullableCacheListRequest {
	return &NullableCacheListRequest{value: val, isSet: true}
}

func (v NullableCacheListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


