/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the AiChatRequestMessagesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiChatRequestMessagesInner{}

// AiChatRequestMessagesInner struct for AiChatRequestMessagesInner
type AiChatRequestMessagesInner struct {
	Role *string `json:"role,omitempty"`
	Content *string `json:"content,omitempty"`
}

// NewAiChatRequestMessagesInner instantiates a new AiChatRequestMessagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiChatRequestMessagesInner() *AiChatRequestMessagesInner {
	this := AiChatRequestMessagesInner{}
	return &this
}

// NewAiChatRequestMessagesInnerWithDefaults instantiates a new AiChatRequestMessagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiChatRequestMessagesInnerWithDefaults() *AiChatRequestMessagesInner {
	this := AiChatRequestMessagesInner{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AiChatRequestMessagesInner) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiChatRequestMessagesInner) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AiChatRequestMessagesInner) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *AiChatRequestMessagesInner) SetRole(v string) {
	o.Role = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *AiChatRequestMessagesInner) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiChatRequestMessagesInner) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *AiChatRequestMessagesInner) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *AiChatRequestMessagesInner) SetContent(v string) {
	o.Content = &v
}

func (o AiChatRequestMessagesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiChatRequestMessagesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

type NullableAiChatRequestMessagesInner struct {
	value *AiChatRequestMessagesInner
	isSet bool
}

func (v NullableAiChatRequestMessagesInner) Get() *AiChatRequestMessagesInner {
	return v.value
}

func (v *NullableAiChatRequestMessagesInner) Set(val *AiChatRequestMessagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAiChatRequestMessagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAiChatRequestMessagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiChatRequestMessagesInner(val *AiChatRequestMessagesInner) *NullableAiChatRequestMessagesInner {
	return &NullableAiChatRequestMessagesInner{value: val, isSet: true}
}

func (v NullableAiChatRequestMessagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiChatRequestMessagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


