/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DbQueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DbQueryRequest{}

// DbQueryRequest struct for DbQueryRequest
type DbQueryRequest struct {
	// SQL query to execute
	Sql string `json:"sql"`
	// Query parameters for prepared statements
	Params []interface{} `json:"params,omitempty"`
}

type _DbQueryRequest DbQueryRequest

// NewDbQueryRequest instantiates a new DbQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDbQueryRequest(sql string) *DbQueryRequest {
	this := DbQueryRequest{}
	this.Sql = sql
	return &this
}

// NewDbQueryRequestWithDefaults instantiates a new DbQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDbQueryRequestWithDefaults() *DbQueryRequest {
	this := DbQueryRequest{}
	return &this
}

// GetSql returns the Sql field value
func (o *DbQueryRequest) GetSql() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sql
}

// GetSqlOk returns a tuple with the Sql field value
// and a boolean to check if the value has been set.
func (o *DbQueryRequest) GetSqlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sql, true
}

// SetSql sets field value
func (o *DbQueryRequest) SetSql(v string) {
	o.Sql = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *DbQueryRequest) GetParams() []interface{} {
	if o == nil || IsNil(o.Params) {
		var ret []interface{}
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DbQueryRequest) GetParamsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *DbQueryRequest) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given []interface{} and assigns it to the Params field.
func (o *DbQueryRequest) SetParams(v []interface{}) {
	o.Params = v
}

func (o DbQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DbQueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sql"] = o.Sql
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	return toSerialize, nil
}

func (o *DbQueryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sql",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDbQueryRequest := _DbQueryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDbQueryRequest)

	if err != nil {
		return err
	}

	*o = DbQueryRequest(varDbQueryRequest)

	return err
}

type NullableDbQueryRequest struct {
	value *DbQueryRequest
	isSet bool
}

func (v NullableDbQueryRequest) Get() *DbQueryRequest {
	return v.value
}

func (v *NullableDbQueryRequest) Set(val *DbQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDbQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDbQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDbQueryRequest(val *DbQueryRequest) *NullableDbQueryRequest {
	return &NullableDbQueryRequest{value: val, isSet: true}
}

func (v NullableDbQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDbQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


