/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the AiChat200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiChat200Response{}

// AiChat200Response struct for AiChat200Response
type AiChat200Response struct {
	Response *string `json:"response,omitempty"`
}

// NewAiChat200Response instantiates a new AiChat200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiChat200Response() *AiChat200Response {
	this := AiChat200Response{}
	return &this
}

// NewAiChat200ResponseWithDefaults instantiates a new AiChat200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiChat200ResponseWithDefaults() *AiChat200Response {
	this := AiChat200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *AiChat200Response) GetResponse() string {
	if o == nil || IsNil(o.Response) {
		var ret string
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiChat200Response) GetResponseOk() (*string, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *AiChat200Response) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given string and assigns it to the Response field.
func (o *AiChat200Response) SetResponse(v string) {
	o.Response = &v
}

func (o AiChat200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiChat200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	return toSerialize, nil
}

type NullableAiChat200Response struct {
	value *AiChat200Response
	isSet bool
}

func (v NullableAiChat200Response) Get() *AiChat200Response {
	return v.value
}

func (v *NullableAiChat200Response) Set(val *AiChat200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAiChat200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAiChat200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiChat200Response(val *AiChat200Response) *NullableAiChat200Response {
	return &NullableAiChat200Response{value: val, isSet: true}
}

func (v NullableAiChat200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiChat200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


