/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the StorageExists200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageExists200Response{}

// StorageExists200Response struct for StorageExists200Response
type StorageExists200Response struct {
	Exists *bool `json:"exists,omitempty"`
}

// NewStorageExists200Response instantiates a new StorageExists200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageExists200Response() *StorageExists200Response {
	this := StorageExists200Response{}
	return &this
}

// NewStorageExists200ResponseWithDefaults instantiates a new StorageExists200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageExists200ResponseWithDefaults() *StorageExists200Response {
	this := StorageExists200Response{}
	return &this
}

// GetExists returns the Exists field value if set, zero value otherwise.
func (o *StorageExists200Response) GetExists() bool {
	if o == nil || IsNil(o.Exists) {
		var ret bool
		return ret
	}
	return *o.Exists
}

// GetExistsOk returns a tuple with the Exists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageExists200Response) GetExistsOk() (*bool, bool) {
	if o == nil || IsNil(o.Exists) {
		return nil, false
	}
	return o.Exists, true
}

// HasExists returns a boolean if a field has been set.
func (o *StorageExists200Response) HasExists() bool {
	if o != nil && !IsNil(o.Exists) {
		return true
	}

	return false
}

// SetExists gets a reference to the given bool and assigns it to the Exists field.
func (o *StorageExists200Response) SetExists(v bool) {
	o.Exists = &v
}

func (o StorageExists200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageExists200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Exists) {
		toSerialize["exists"] = o.Exists
	}
	return toSerialize, nil
}

type NullableStorageExists200Response struct {
	value *StorageExists200Response
	isSet bool
}

func (v NullableStorageExists200Response) Get() *StorageExists200Response {
	return v.value
}

func (v *NullableStorageExists200Response) Set(val *StorageExists200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageExists200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageExists200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageExists200Response(val *StorageExists200Response) *NullableStorageExists200Response {
	return &NullableStorageExists200Response{value: val, isSet: true}
}

func (v NullableStorageExists200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageExists200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


