/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the QueueCancelJob200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueCancelJob200Response{}

// QueueCancelJob200Response struct for QueueCancelJob200Response
type QueueCancelJob200Response struct {
	Success *bool `json:"success,omitempty"`
	// Optional advisory note (e.g. already in terminal state)
	Note *string `json:"note,omitempty"`
}

// NewQueueCancelJob200Response instantiates a new QueueCancelJob200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueCancelJob200Response() *QueueCancelJob200Response {
	this := QueueCancelJob200Response{}
	return &this
}

// NewQueueCancelJob200ResponseWithDefaults instantiates a new QueueCancelJob200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueCancelJob200ResponseWithDefaults() *QueueCancelJob200Response {
	this := QueueCancelJob200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *QueueCancelJob200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueCancelJob200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *QueueCancelJob200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *QueueCancelJob200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *QueueCancelJob200Response) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueCancelJob200Response) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *QueueCancelJob200Response) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *QueueCancelJob200Response) SetNote(v string) {
	o.Note = &v
}

func (o QueueCancelJob200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueCancelJob200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	return toSerialize, nil
}

type NullableQueueCancelJob200Response struct {
	value *QueueCancelJob200Response
	isSet bool
}

func (v NullableQueueCancelJob200Response) Get() *QueueCancelJob200Response {
	return v.value
}

func (v *NullableQueueCancelJob200Response) Set(val *QueueCancelJob200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueCancelJob200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueCancelJob200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueCancelJob200Response(val *QueueCancelJob200Response) *NullableQueueCancelJob200Response {
	return &NullableQueueCancelJob200Response{value: val, isSet: true}
}

func (v NullableQueueCancelJob200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueCancelJob200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


