/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the CacheSet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheSet200Response{}

// CacheSet200Response struct for CacheSet200Response
type CacheSet200Response struct {
	Success *bool `json:"success,omitempty"`
}

// NewCacheSet200Response instantiates a new CacheSet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheSet200Response() *CacheSet200Response {
	this := CacheSet200Response{}
	return &this
}

// NewCacheSet200ResponseWithDefaults instantiates a new CacheSet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheSet200ResponseWithDefaults() *CacheSet200Response {
	this := CacheSet200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CacheSet200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheSet200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CacheSet200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CacheSet200Response) SetSuccess(v bool) {
	o.Success = &v
}

func (o CacheSet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheSet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableCacheSet200Response struct {
	value *CacheSet200Response
	isSet bool
}

func (v NullableCacheSet200Response) Get() *CacheSet200Response {
	return v.value
}

func (v *NullableCacheSet200Response) Set(val *CacheSet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheSet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheSet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheSet200Response(val *CacheSet200Response) *NullableCacheSet200Response {
	return &NullableCacheSet200Response{value: val, isSet: true}
}

func (v NullableCacheSet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheSet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


