/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StorageMoveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageMoveRequest{}

// StorageMoveRequest struct for StorageMoveRequest
type StorageMoveRequest struct {
	SourceKey string `json:"sourceKey"`
	DestKey string `json:"destKey"`
}

type _StorageMoveRequest StorageMoveRequest

// NewStorageMoveRequest instantiates a new StorageMoveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageMoveRequest(sourceKey string, destKey string) *StorageMoveRequest {
	this := StorageMoveRequest{}
	this.SourceKey = sourceKey
	this.DestKey = destKey
	return &this
}

// NewStorageMoveRequestWithDefaults instantiates a new StorageMoveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageMoveRequestWithDefaults() *StorageMoveRequest {
	this := StorageMoveRequest{}
	return &this
}

// GetSourceKey returns the SourceKey field value
func (o *StorageMoveRequest) GetSourceKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceKey
}

// GetSourceKeyOk returns a tuple with the SourceKey field value
// and a boolean to check if the value has been set.
func (o *StorageMoveRequest) GetSourceKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceKey, true
}

// SetSourceKey sets field value
func (o *StorageMoveRequest) SetSourceKey(v string) {
	o.SourceKey = v
}

// GetDestKey returns the DestKey field value
func (o *StorageMoveRequest) GetDestKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestKey
}

// GetDestKeyOk returns a tuple with the DestKey field value
// and a boolean to check if the value has been set.
func (o *StorageMoveRequest) GetDestKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestKey, true
}

// SetDestKey sets field value
func (o *StorageMoveRequest) SetDestKey(v string) {
	o.DestKey = v
}

func (o StorageMoveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageMoveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sourceKey"] = o.SourceKey
	toSerialize["destKey"] = o.DestKey
	return toSerialize, nil
}

func (o *StorageMoveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sourceKey",
		"destKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageMoveRequest := _StorageMoveRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStorageMoveRequest)

	if err != nil {
		return err
	}

	*o = StorageMoveRequest(varStorageMoveRequest)

	return err
}

type NullableStorageMoveRequest struct {
	value *StorageMoveRequest
	isSet bool
}

func (v NullableStorageMoveRequest) Get() *StorageMoveRequest {
	return v.value
}

func (v *NullableStorageMoveRequest) Set(val *StorageMoveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageMoveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageMoveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageMoveRequest(val *StorageMoveRequest) *NullableStorageMoveRequest {
	return &NullableStorageMoveRequest{value: val, isSet: true}
}

func (v NullableStorageMoveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageMoveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


