/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AiChatRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiChatRequest{}

// AiChatRequest struct for AiChatRequest
type AiChatRequest struct {
	Model *string `json:"model,omitempty"`
	Messages []AiChatRequestMessagesInner `json:"messages"`
}

type _AiChatRequest AiChatRequest

// NewAiChatRequest instantiates a new AiChatRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiChatRequest(messages []AiChatRequestMessagesInner) *AiChatRequest {
	this := AiChatRequest{}
	this.Messages = messages
	return &this
}

// NewAiChatRequestWithDefaults instantiates a new AiChatRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiChatRequestWithDefaults() *AiChatRequest {
	this := AiChatRequest{}
	return &this
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *AiChatRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiChatRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *AiChatRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *AiChatRequest) SetModel(v string) {
	o.Model = &v
}

// GetMessages returns the Messages field value
func (o *AiChatRequest) GetMessages() []AiChatRequestMessagesInner {
	if o == nil {
		var ret []AiChatRequestMessagesInner
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *AiChatRequest) GetMessagesOk() ([]AiChatRequestMessagesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *AiChatRequest) SetMessages(v []AiChatRequestMessagesInner) {
	o.Messages = v
}

func (o AiChatRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiChatRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	toSerialize["messages"] = o.Messages
	return toSerialize, nil
}

func (o *AiChatRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAiChatRequest := _AiChatRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAiChatRequest)

	if err != nil {
		return err
	}

	*o = AiChatRequest(varAiChatRequest)

	return err
}

type NullableAiChatRequest struct {
	value *AiChatRequest
	isSet bool
}

func (v NullableAiChatRequest) Get() *AiChatRequest {
	return v.value
}

func (v *NullableAiChatRequest) Set(val *AiChatRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAiChatRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAiChatRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiChatRequest(val *AiChatRequest) *NullableAiChatRequest {
	return &NullableAiChatRequest{value: val, isSet: true}
}

func (v NullableAiChatRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiChatRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


