/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the CacheKeysRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheKeysRequest{}

// CacheKeysRequest struct for CacheKeysRequest
type CacheKeysRequest struct {
	// Key prefix to filter by
	Prefix *string `json:"prefix,omitempty"`
}

// NewCacheKeysRequest instantiates a new CacheKeysRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheKeysRequest() *CacheKeysRequest {
	this := CacheKeysRequest{}
	return &this
}

// NewCacheKeysRequestWithDefaults instantiates a new CacheKeysRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheKeysRequestWithDefaults() *CacheKeysRequest {
	this := CacheKeysRequest{}
	return &this
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *CacheKeysRequest) GetPrefix() string {
	if o == nil || IsNil(o.Prefix) {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheKeysRequest) GetPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *CacheKeysRequest) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *CacheKeysRequest) SetPrefix(v string) {
	o.Prefix = &v
}

func (o CacheKeysRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheKeysRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	return toSerialize, nil
}

type NullableCacheKeysRequest struct {
	value *CacheKeysRequest
	isSet bool
}

func (v NullableCacheKeysRequest) Get() *CacheKeysRequest {
	return v.value
}

func (v *NullableCacheKeysRequest) Set(val *CacheKeysRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheKeysRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheKeysRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheKeysRequest(val *CacheKeysRequest) *NullableCacheKeysRequest {
	return &NullableCacheKeysRequest{value: val, isSet: true}
}

func (v NullableCacheKeysRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheKeysRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


