/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"time"
)

// checks if the StorageObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageObject{}

// StorageObject struct for StorageObject
type StorageObject struct {
	// Storage key (project prefix stripped)
	Key *string `json:"key,omitempty"`
	// File size in bytes
	Size *int32 `json:"size,omitempty"`
	LastModified *time.Time `json:"lastModified,omitempty"`
	ContentType *string `json:"contentType,omitempty"`
	Etag *string `json:"etag,omitempty"`
}

// NewStorageObject instantiates a new StorageObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageObject() *StorageObject {
	this := StorageObject{}
	return &this
}

// NewStorageObjectWithDefaults instantiates a new StorageObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageObjectWithDefaults() *StorageObject {
	this := StorageObject{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *StorageObject) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageObject) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *StorageObject) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *StorageObject) SetKey(v string) {
	o.Key = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *StorageObject) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageObject) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *StorageObject) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *StorageObject) SetSize(v int32) {
	o.Size = &v
}

// GetLastModified returns the LastModified field value if set, zero value otherwise.
func (o *StorageObject) GetLastModified() time.Time {
	if o == nil || IsNil(o.LastModified) {
		var ret time.Time
		return ret
	}
	return *o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageObject) GetLastModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastModified) {
		return nil, false
	}
	return o.LastModified, true
}

// HasLastModified returns a boolean if a field has been set.
func (o *StorageObject) HasLastModified() bool {
	if o != nil && !IsNil(o.LastModified) {
		return true
	}

	return false
}

// SetLastModified gets a reference to the given time.Time and assigns it to the LastModified field.
func (o *StorageObject) SetLastModified(v time.Time) {
	o.LastModified = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *StorageObject) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageObject) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *StorageObject) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *StorageObject) SetContentType(v string) {
	o.ContentType = &v
}

// GetEtag returns the Etag field value if set, zero value otherwise.
func (o *StorageObject) GetEtag() string {
	if o == nil || IsNil(o.Etag) {
		var ret string
		return ret
	}
	return *o.Etag
}

// GetEtagOk returns a tuple with the Etag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageObject) GetEtagOk() (*string, bool) {
	if o == nil || IsNil(o.Etag) {
		return nil, false
	}
	return o.Etag, true
}

// HasEtag returns a boolean if a field has been set.
func (o *StorageObject) HasEtag() bool {
	if o != nil && !IsNil(o.Etag) {
		return true
	}

	return false
}

// SetEtag gets a reference to the given string and assigns it to the Etag field.
func (o *StorageObject) SetEtag(v string) {
	o.Etag = &v
}

func (o StorageObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.LastModified) {
		toSerialize["lastModified"] = o.LastModified
	}
	if !IsNil(o.ContentType) {
		toSerialize["contentType"] = o.ContentType
	}
	if !IsNil(o.Etag) {
		toSerialize["etag"] = o.Etag
	}
	return toSerialize, nil
}

type NullableStorageObject struct {
	value *StorageObject
	isSet bool
}

func (v NullableStorageObject) Get() *StorageObject {
	return v.value
}

func (v *NullableStorageObject) Set(val *StorageObject) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageObject) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageObject(val *StorageObject) *NullableStorageObject {
	return &NullableStorageObject{value: val, isSet: true}
}

func (v NullableStorageObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


