/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication, caching, queues, storage, and AI services. 

API version: 1.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
)

// checks if the CacheSetMany200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheSetMany200Response{}

// CacheSetMany200Response struct for CacheSetMany200Response
type CacheSetMany200Response struct {
	Success *bool `json:"success,omitempty"`
	// Number of entries stored
	Count *int32 `json:"count,omitempty"`
}

// NewCacheSetMany200Response instantiates a new CacheSetMany200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheSetMany200Response() *CacheSetMany200Response {
	this := CacheSetMany200Response{}
	return &this
}

// NewCacheSetMany200ResponseWithDefaults instantiates a new CacheSetMany200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheSetMany200ResponseWithDefaults() *CacheSetMany200Response {
	this := CacheSetMany200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CacheSetMany200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheSetMany200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CacheSetMany200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CacheSetMany200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *CacheSetMany200Response) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheSetMany200Response) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *CacheSetMany200Response) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *CacheSetMany200Response) SetCount(v int32) {
	o.Count = &v
}

func (o CacheSetMany200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheSetMany200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableCacheSetMany200Response struct {
	value *CacheSetMany200Response
	isSet bool
}

func (v NullableCacheSetMany200Response) Get() *CacheSetMany200Response {
	return v.value
}

func (v *NullableCacheSetMany200Response) Set(val *CacheSetMany200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheSetMany200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheSetMany200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheSetMany200Response(val *CacheSetMany200Response) *NullableCacheSetMany200Response {
	return &NullableCacheSetMany200Response{value: val, isSet: true}
}

func (v NullableCacheSetMany200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheSetMany200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


