/*
Aerostack API

Aerostack Platform API - Unified access to database, authentication,  caching, queues, storage, and AI services. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aerostack

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CacheSetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheSetRequest{}

// CacheSetRequest struct for CacheSetRequest
type CacheSetRequest struct {
	Key string `json:"key"`
	Value interface{} `json:"value"`
	// Time to live in seconds
	Ttl *int32 `json:"ttl,omitempty"`
}

type _CacheSetRequest CacheSetRequest

// NewCacheSetRequest instantiates a new CacheSetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheSetRequest(key string, value interface{}) *CacheSetRequest {
	this := CacheSetRequest{}
	this.Key = key
	this.Value = value
	return &this
}

// NewCacheSetRequestWithDefaults instantiates a new CacheSetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheSetRequestWithDefaults() *CacheSetRequest {
	this := CacheSetRequest{}
	return &this
}

// GetKey returns the Key field value
func (o *CacheSetRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *CacheSetRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *CacheSetRequest) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CacheSetRequest) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CacheSetRequest) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CacheSetRequest) SetValue(v interface{}) {
	o.Value = v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *CacheSetRequest) GetTtl() int32 {
	if o == nil || IsNil(o.Ttl) {
		var ret int32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CacheSetRequest) GetTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *CacheSetRequest) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given int32 and assigns it to the Ttl field.
func (o *CacheSetRequest) SetTtl(v int32) {
	o.Ttl = &v
}

func (o CacheSetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheSetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	return toSerialize, nil
}

func (o *CacheSetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCacheSetRequest := _CacheSetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCacheSetRequest)

	if err != nil {
		return err
	}

	*o = CacheSetRequest(varCacheSetRequest)

	return err
}

type NullableCacheSetRequest struct {
	value *CacheSetRequest
	isSet bool
}

func (v NullableCacheSetRequest) Get() *CacheSetRequest {
	return v.value
}

func (v *NullableCacheSetRequest) Set(val *CacheSetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheSetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheSetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheSetRequest(val *CacheSetRequest) *NullableCacheSetRequest {
	return &NullableCacheSetRequest{value: val, isSet: true}
}

func (v NullableCacheSetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheSetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


