// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/aerostackdev/sdks/packages/go/pkg/models/shared"
	"net/http"
)

type AuthSigninRequestBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (a *AuthSigninRequestBody) GetEmail() string {
	if a == nil {
		return ""
	}
	return a.Email
}

func (a *AuthSigninRequestBody) GetPassword() string {
	if a == nil {
		return ""
	}
	return a.Password
}

type AuthSigninResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// User authenticated successfully
	AuthResponse *shared.AuthResponse
}

func (a *AuthSigninResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AuthSigninResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AuthSigninResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AuthSigninResponse) GetAuthResponse() *shared.AuthResponse {
	if a == nil {
		return nil
	}
	return a.AuthResponse
}
