// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
	"undefined/pkg/models/shared"
)

type AuthSignupRequestBody struct {
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Name     *string        `json:"name,omitempty"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

func (a *AuthSignupRequestBody) GetEmail() string {
	if a == nil {
		return ""
	}
	return a.Email
}

func (a *AuthSignupRequestBody) GetPassword() string {
	if a == nil {
		return ""
	}
	return a.Password
}

func (a *AuthSignupRequestBody) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AuthSignupRequestBody) GetMetadata() map[string]any {
	if a == nil {
		return nil
	}
	return a.Metadata
}

type AuthSignupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// User created successfully
	AuthResponse *shared.AuthResponse
}

func (a *AuthSignupResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AuthSignupResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AuthSignupResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AuthSignupResponse) GetAuthResponse() *shared.AuthResponse {
	if a == nil {
		return nil
	}
	return a.AuthResponse
}
