// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

type EmbeddingModel string

const (
	EmbeddingModelEnglish      EmbeddingModel = "english"
	EmbeddingModelMultilingual EmbeddingModel = "multilingual"
)

func (e EmbeddingModel) ToPointer() *EmbeddingModel {
	return &e
}
func (e *EmbeddingModel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "english":
		fallthrough
	case "multilingual":
		*e = EmbeddingModel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EmbeddingModel: %v", v)
	}
}

type ConfigureRequestBody struct {
	EmbeddingModel EmbeddingModel `json:"embeddingModel"`
}

func (c *ConfigureRequestBody) GetEmbeddingModel() EmbeddingModel {
	if c == nil {
		return EmbeddingModel("")
	}
	return c.EmbeddingModel
}

// ConfigureResponseBody - Configured
type ConfigureResponseBody struct {
	Success *bool `json:"success,omitempty"`
}

func (c *ConfigureResponseBody) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

type ConfigureResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Configured
	Object *ConfigureResponseBody
}

func (c *ConfigureResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *ConfigureResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *ConfigureResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *ConfigureResponse) GetObject() *ConfigureResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
