// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/aerostackdev/sdks/packages/go/pkg/models/shared"
	"net/http"
)

type DbQueryRequestBody struct {
	// SQL query to execute
	SQL string `json:"sql"`
	// Query parameters for prepared statements
	Params []any `json:"params,omitempty"`
}

func (d *DbQueryRequestBody) GetSQL() string {
	if d == nil {
		return ""
	}
	return d.SQL
}

func (d *DbQueryRequestBody) GetParams() []any {
	if d == nil {
		return nil
	}
	return d.Params
}

type DbQueryRequest struct {
	// Unique request tracing ID
	XRequestID *string `header:"style=simple,explode=false,name=X-Request-ID"`
	// SDK version string
	XSDKVersion *string            `header:"style=simple,explode=false,name=X-SDK-Version"`
	RequestBody DbQueryRequestBody `request:"mediaType=application/json"`
}

func (d *DbQueryRequest) GetXRequestID() *string {
	if d == nil {
		return nil
	}
	return d.XRequestID
}

func (d *DbQueryRequest) GetXSDKVersion() *string {
	if d == nil {
		return nil
	}
	return d.XSDKVersion
}

func (d *DbQueryRequest) GetRequestBody() DbQueryRequestBody {
	if d == nil {
		return DbQueryRequestBody{}
	}
	return d.RequestBody
}

type DbQueryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Query executed successfully
	DbQueryResult *shared.DbQueryResult
}

func (d *DbQueryResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DbQueryResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DbQueryResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DbQueryResponse) GetDbQueryResult() *shared.DbQueryResult {
	if d == nil {
		return nil
	}
	return d.DbQueryResult
}
