// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteByTypeRequestBody struct {
	Type string `json:"type"`
}

func (d *DeleteByTypeRequestBody) GetType() string {
	if d == nil {
		return ""
	}
	return d.Type
}

// DeleteByTypeResponseBody - Deleted
type DeleteByTypeResponseBody struct {
	Success *bool `json:"success,omitempty"`
}

func (d *DeleteByTypeResponseBody) GetSuccess() *bool {
	if d == nil {
		return nil
	}
	return d.Success
}

type DeleteByTypeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Deleted
	Object *DeleteByTypeResponseBody
}

func (d *DeleteByTypeResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteByTypeResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteByTypeResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteByTypeResponse) GetObject() *DeleteByTypeResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
