// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GatewayBillingLogRequestBody struct {
	// The Consumer ID making the request
	ConsumerID string `json:"consumerId"`
	// The Developer Gateway API ID being consumed
	APIID string `json:"apiId"`
	// Optional metric name (default: 'units')
	Metric *string `json:"metric,omitempty"`
	// Amount of usage to log
	Units int64 `json:"units"`
}

func (g *GatewayBillingLogRequestBody) GetConsumerID() string {
	if g == nil {
		return ""
	}
	return g.ConsumerID
}

func (g *GatewayBillingLogRequestBody) GetAPIID() string {
	if g == nil {
		return ""
	}
	return g.APIID
}

func (g *GatewayBillingLogRequestBody) GetMetric() *string {
	if g == nil {
		return nil
	}
	return g.Metric
}

func (g *GatewayBillingLogRequestBody) GetUnits() int64 {
	if g == nil {
		return 0
	}
	return g.Units
}

// GatewayBillingLogResponseBody - Usage logged successfully
type GatewayBillingLogResponseBody struct {
	Success     *bool  `json:"success,omitempty"`
	LoggedUnits *int64 `json:"loggedUnits,omitempty"`
}

func (g *GatewayBillingLogResponseBody) GetSuccess() *bool {
	if g == nil {
		return nil
	}
	return g.Success
}

func (g *GatewayBillingLogResponseBody) GetLoggedUnits() *int64 {
	if g == nil {
		return nil
	}
	return g.LoggedUnits
}

type GatewayBillingLogResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Usage logged successfully
	Object *GatewayBillingLogResponseBody
}

func (g *GatewayBillingLogResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GatewayBillingLogResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GatewayBillingLogResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GatewayBillingLogResponse) GetObject() *GatewayBillingLogResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
