// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type IngestRequestBody struct {
	// Text content to index
	Content string `json:"content"`
	// Optional custom ID
	ID *string `json:"id,omitempty"`
	// Category/type of content
	Type     string         `json:"type"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

func (i *IngestRequestBody) GetContent() string {
	if i == nil {
		return ""
	}
	return i.Content
}

func (i *IngestRequestBody) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *IngestRequestBody) GetType() string {
	if i == nil {
		return ""
	}
	return i.Type
}

func (i *IngestRequestBody) GetMetadata() map[string]any {
	if i == nil {
		return nil
	}
	return i.Metadata
}

// IngestResponseBody - Content ingested successfully
type IngestResponseBody struct {
	Success *bool `json:"success,omitempty"`
}

func (i *IngestResponseBody) GetSuccess() *bool {
	if i == nil {
		return nil
	}
	return i.Success
}

type IngestResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Content ingested successfully
	Object *IngestResponseBody
}

func (i *IngestResponse) GetContentType() string {
	if i == nil {
		return ""
	}
	return i.ContentType
}

func (i *IngestResponse) GetStatusCode() int {
	if i == nil {
		return 0
	}
	return i.StatusCode
}

func (i *IngestResponse) GetRawResponse() *http.Response {
	if i == nil {
		return nil
	}
	return i.RawResponse
}

func (i *IngestResponse) GetObject() *IngestResponseBody {
	if i == nil {
		return nil
	}
	return i.Object
}
