// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/aerostackdev/sdks/packages/go/pkg/models/shared"
	"net/http"
)

// ListTypesResponseBody - Type statistics
type ListTypesResponseBody struct {
	Types []shared.TypeStats `json:"types,omitempty"`
}

func (l *ListTypesResponseBody) GetTypes() []shared.TypeStats {
	if l == nil {
		return nil
	}
	return l.Types
}

type ListTypesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Type statistics
	Object *ListTypesResponseBody
}

func (l *ListTypesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListTypesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListTypesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListTypesResponse) GetObject() *ListTypesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
