// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/aerostackdev/sdks/packages/go/pkg/models/shared"
	"github.com/aerostackdev/sdks/packages/go/pkg/utils"
	"net/http"
)

type QueryRequestBody struct {
	Text   string         `json:"text"`
	TopK   *int64         `default:"5" json:"topK"`
	Types  []string       `json:"types,omitempty"`
	Filter map[string]any `json:"filter,omitempty"`
}

func (q QueryRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryRequestBody) GetText() string {
	if q == nil {
		return ""
	}
	return q.Text
}

func (q *QueryRequestBody) GetTopK() *int64 {
	if q == nil {
		return nil
	}
	return q.TopK
}

func (q *QueryRequestBody) GetTypes() []string {
	if q == nil {
		return nil
	}
	return q.Types
}

func (q *QueryRequestBody) GetFilter() map[string]any {
	if q == nil {
		return nil
	}
	return q.Filter
}

// QueryResponseBody - Search results
type QueryResponseBody struct {
	Results []shared.SearchResult `json:"results,omitempty"`
}

func (q *QueryResponseBody) GetResults() []shared.SearchResult {
	if q == nil {
		return nil
	}
	return q.Results
}

type QueryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Search results
	Object *QueryResponseBody
}

func (q *QueryResponse) GetContentType() string {
	if q == nil {
		return ""
	}
	return q.ContentType
}

func (q *QueryResponse) GetStatusCode() int {
	if q == nil {
		return 0
	}
	return q.StatusCode
}

func (q *QueryResponse) GetRawResponse() *http.Response {
	if q == nil {
		return nil
	}
	return q.RawResponse
}

func (q *QueryResponse) GetObject() *QueryResponseBody {
	if q == nil {
		return nil
	}
	return q.Object
}
