// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SearchResult struct {
	ID       *string        `json:"id,omitempty"`
	Content  *string        `json:"content,omitempty"`
	Score    *float64       `json:"score,omitempty"`
	Type     *string        `json:"type,omitempty"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

func (s *SearchResult) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *SearchResult) GetContent() *string {
	if s == nil {
		return nil
	}
	return s.Content
}

func (s *SearchResult) GetScore() *float64 {
	if s == nil {
		return nil
	}
	return s.Score
}

func (s *SearchResult) GetType() *string {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *SearchResult) GetMetadata() map[string]any {
	if s == nil {
		return nil
	}
	return s.Metadata
}
