// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TypeStats struct {
	Type  *string `json:"type,omitempty"`
	Count *int64  `json:"count,omitempty"`
}

func (t *TypeStats) GetType() *string {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *TypeStats) GetCount() *int64 {
	if t == nil {
		return nil
	}
	return t.Count
}
